#!/usr/bin/env python3
# =============================================================================
# config_resolver.py
# Generated by: synthetic-data-generator | Date: 2026-02-24
# Updated by: demo-scope-configurator | Date: 2026-02-28
# Purpose: Merge config.yaml overrides on top of value_pools defaults.
#          Resolve preset profiles, depth, and complexity settings.
# Assumptions: value_pools.py provides fallback constants for all pools.
# =============================================================================

"""Config resolution layer: merges YAML overrides on top of value_pools defaults.

Public functions:
- resolve_defaults(cfg) — merge cfg["defaults"] on top of value_pools constants
- resolve_region(cfg)   — read cfg["region"] with Czech fallbacks
- resolve_preset(preset_name, base_cfg) — load preset YAML and merge into config
- resolve_depth(cfg)    — interpret depth settings (cascade levels, slots)
- resolve_complexity(cfg, pools) — interpret complexity settings (vendor mode, variety)
- get_enum_with_weights — read entity-level enum/weights with fallbacks
"""

import copy
import logging
from pathlib import Path

from value_pools import (
    FIBER_TYPES,
    OLT_CHASSIS,
    OLT_VENDORS,
    OLT_VENDOR_WEIGHTS,
    ONT_MODEL_WEIGHTS,
    ONT_MODELS,
    ONT_STATUS_WEIGHTS,
    ONT_STATUSES,
    OLT_STATUS_WEIGHTS,
    OLT_STATUSES,
    SFP_CLASSES,
    SFP_CLASS_WEIGHTS,
    SFP_WAVELENGTH,
    SITE_NAMES,
    SITE_STATUS_WEIGHTS,
    SITE_STATUSES,
    SPLIT_RATIO_WEIGHTS,
    SPLIT_RATIOS,
)

log = logging.getLogger(__name__)

# Try to load PyYAML
try:
    import yaml  # type: ignore[import-untyped]
except ImportError:
    yaml = None  # type: ignore[assignment]

PROFILES_DIR = Path(__file__).resolve().parent.parent / "profiles"

PRESET_NAMES = ("minimal", "small", "medium", "large", "stress-test")

# Region name → profile filename mapping
REGION_ALIASES = {
    "czech": None,  # use base config.yaml defaults
    "bratislava": "config-bratislava.yaml",
    "vienna": "config-vienna.yaml",
}


def _deep_merge(base: dict, override: dict) -> dict:
    """Deep-merge *override* into a copy of *base*. Lists are replaced, not appended."""
    result = copy.deepcopy(base)
    for key, val in override.items():
        if key in result and isinstance(result[key], dict) and isinstance(val, dict):
            result[key] = _deep_merge(result[key], val)
        else:
            result[key] = copy.deepcopy(val)
    return result


def _load_yaml(path: Path) -> dict:
    """Load a YAML file. Requires PyYAML."""
    if yaml is None:
        raise ImportError("PyYAML is required to load preset/region profiles")
    with open(path) as f:
        return yaml.safe_load(f) or {}


def resolve_preset(preset_name: str, base_cfg: dict) -> dict:
    """Load a preset YAML and merge size/depth/complexity into base config.

    Merge order: base_cfg ← preset values.
    Only size, depth, and complexity sections are taken from presets.
    """
    if preset_name not in PRESET_NAMES:
        raise ValueError(f"Unknown preset: {preset_name!r}. Choose from: {PRESET_NAMES}")

    preset_path = PROFILES_DIR / f"preset-{preset_name}.yaml"
    if not preset_path.exists():
        raise FileNotFoundError(f"Preset file not found: {preset_path}")

    preset = _load_yaml(preset_path)
    result = copy.deepcopy(base_cfg)

    # Apply size → entity volumes
    size = preset.get("size", {})
    if size:
        entities = result.setdefault("entities", {})
        volume_map = {
            "sites": "site",
            "olts": "olt",
            "splitters": "splitter",
            "onts": "ont",
        }
        for size_key, entity_name in volume_map.items():
            if size_key in size:
                entities.setdefault(entity_name, {})["volume"] = size[size_key]

    # Apply depth and complexity as top-level sections
    for section in ("depth", "complexity"):
        if section in preset:
            result[section] = _deep_merge(result.get(section, {}), preset[section])

    log.info("Applied preset '%s': %s", preset_name, size)
    return result


def resolve_region_profile(region_name: str, base_cfg: dict) -> dict:
    """Load a region profile and merge region/defaults into config.

    If region_name is a file path, load it directly.
    If it's an alias (czech, bratislava, vienna), look up the profile.
    """
    if region_name in REGION_ALIASES:
        profile_file = REGION_ALIASES[region_name]
        if profile_file is None:
            # "czech" = use base config defaults, no override
            return base_cfg
        region_path = PROFILES_DIR / profile_file
    else:
        # Treat as a file path
        region_path = Path(region_name)

    if not region_path.exists():
        raise FileNotFoundError(f"Region profile not found: {region_path}")

    region_cfg = _load_yaml(region_path)
    result = copy.deepcopy(base_cfg)

    # Merge region and defaults sections only
    if "region" in region_cfg:
        result["region"] = _deep_merge(result.get("region", {}), region_cfg["region"])
    if "defaults" in region_cfg:
        result["defaults"] = _deep_merge(result.get("defaults", {}), region_cfg["defaults"])

    log.info("Applied region profile: %s", region_path.name)
    return result


def resolve_depth(cfg: dict) -> dict:
    """Return depth settings with defaults filled in."""
    defaults = {
        "splitter_cascade_levels": 1,
        "cascade_ratio": 0.0,
        "slots_per_olt": [2, 4],
    }
    depth = cfg.get("depth", {})
    if not depth:
        return defaults
    return _deep_merge(defaults, depth)


def resolve_complexity(cfg: dict, pools: dict) -> dict:
    """Apply complexity settings to pools dict and return complexity config.

    Modifies pools in place:
    - vendor_mode=single: restrict to primary_vendor only
    - ont_model_variety=low: keep only 2 ONT models
    - failure_rate_percent: adjust ONT status weights
    """
    defaults = {
        "vendor_mode": "multi",
        "primary_vendor": "Huawei",
        "ont_model_variety": "normal",
        "failure_rate_percent": 5,
    }
    complexity = _deep_merge(defaults, cfg.get("complexity", {}))

    # Apply vendor mode
    if complexity["vendor_mode"] == "single":
        primary = complexity["primary_vendor"]
        if primary in pools["olt_vendors"]:
            pools["olt_vendors"] = {primary: pools["olt_vendors"][primary]}
            pools["olt_vendor_weights"] = [1.0]
            pools["olt_chassis"] = {primary: pools["olt_chassis"][primary]}
            log.info("Complexity: single-vendor mode (%s)", primary)

    # Apply ONT model variety
    if complexity["ont_model_variety"] == "low":
        # Keep only first 2 models
        model_names = list(pools["ont_models"].keys())[:2]
        pools["ont_models"] = {k: pools["ont_models"][k] for k in model_names}
        total = sum(pools["ont_model_weights"][:2])
        pools["ont_model_weights"] = [w / total for w in pools["ont_model_weights"][:2]]
        log.info("Complexity: low ONT model variety (%s)", model_names)

    # Apply failure rate
    fail_pct = complexity["failure_rate_percent"]
    if fail_pct == 0:
        pools["ont_statuses"] = ["ACTIVE"]
        pools["ont_status_weights"] = [1.0]
        pools["olt_statuses"] = ["IN_SERVICE"]
        pools["olt_status_weights"] = [1.0]
        pools["site_statuses"] = ["ACTIVE"]
        pools["site_status_weights"] = [1.0]
    elif fail_pct != 5:  # 5 is the default, don't change
        # Scale non-ACTIVE weights proportionally
        active_pct = (100 - fail_pct) / 100.0
        pools["ont_status_weights"] = [active_pct, fail_pct / 200.0, fail_pct / 200.0]

    return complexity


def resolve_defaults(cfg: dict) -> dict:
    """Return a flat pools dict by merging cfg["defaults"] on top of value_pools constants."""
    pools = {
        "olt_vendors": copy.deepcopy(OLT_VENDORS),
        "olt_vendor_weights": list(OLT_VENDOR_WEIGHTS),
        "olt_chassis": copy.deepcopy(OLT_CHASSIS),
        "olt_statuses": list(OLT_STATUSES),
        "olt_status_weights": list(OLT_STATUS_WEIGHTS),
        "ont_models": copy.deepcopy(ONT_MODELS),
        "ont_model_weights": list(ONT_MODEL_WEIGHTS),
        "ont_statuses": list(ONT_STATUSES),
        "ont_status_weights": list(ONT_STATUS_WEIGHTS),
        "site_statuses": list(SITE_STATUSES),
        "site_status_weights": list(SITE_STATUS_WEIGHTS),
        "split_ratios": list(SPLIT_RATIOS),
        "split_ratio_weights": list(SPLIT_RATIO_WEIGHTS),
        "sfp_classes": list(SFP_CLASSES),
        "sfp_class_weights": list(SFP_CLASS_WEIGHTS),
        "sfp_wavelength": SFP_WAVELENGTH,
        "fiber_types": copy.deepcopy(FIBER_TYPES),
    }

    overrides = cfg.get("defaults", {})
    if not overrides:
        return pools

    # Top-level keys in defaults are replaced wholesale, not deep-merged.
    # This means overriding olt_vendors with 2 vendors replaces all 3 defaults.
    for key, val in overrides.items():
        if key in pools:
            pools[key] = copy.deepcopy(val)

    return pools


def resolve_region(cfg: dict) -> dict:
    """Return a region dict with site names and lat/lng bounds."""
    defaults = {
        "name": "Czech Republic - Central",
        "site_names": list(SITE_NAMES),
        "latitude": {"min": 48.0, "max": 50.1},
        "longitude": {"min": 14.0, "max": 18.7},
    }
    region_cfg = cfg.get("region")
    if not region_cfg:
        return defaults
    return _deep_merge(defaults, region_cfg)


def get_enum_with_weights(
    entity_cfg: dict,
    attr_name: str,
    default_values: list,
    default_weights: list,
) -> tuple[list, list]:
    """Read enum and weights for an attribute from entity config, with fallbacks."""
    attrs = entity_cfg.get("attributes", {})
    attr_def = attrs.get(attr_name, {})
    values = attr_def.get("enum", default_values)
    weights = attr_def.get("weights", default_weights)
    return values, weights
