#!/usr/bin/env python3
# =============================================================================
# generate_synthetic_data.py
# Generated by: synthetic-data-generator | Date: 2026-02-19
# Purpose: Generate synthetic GPON CSV data from config.yaml definitions.
# Assumptions: Python 3.10+, no external dependencies (stdlib only).
# =============================================================================

"""Generate synthetic GPON inventory data as CSV files.

Usage::

    python generate_synthetic_data.py --config config.yaml --output-dir ./output --seed 42

Produces sites.csv, olts.csv, splitters.csv, onts.csv, connections.csv,
and a manifest.json with file list, row counts, and SHA-256 checksums.
"""

import argparse
import csv
import hashlib
import json
import logging
import math
import os
import random
import sys
from pathlib import Path

from config_resolver import (
    get_enum_with_weights,
    resolve_complexity,
    resolve_defaults,
    resolve_depth,
    resolve_region,
)

log = logging.getLogger(__name__)

# Try to load PyYAML; fall back to a minimal parser for simple configs.
try:
    import yaml  # type: ignore[import-untyped]
except ImportError:
    yaml = None  # type: ignore[assignment]


# ---------------------------------------------------------------------------
# Minimal YAML-subset parser (used only when PyYAML is not installed)
# ---------------------------------------------------------------------------

def _minimal_yaml_load(path: Path) -> dict:
    """Parse the subset of YAML used by config.yaml without PyYAML.

    Supports top-level scalars, one level of mapping nesting, and simple
    inline lists / dicts.  Sufficient for the demo config but not a general
    YAML parser.
    """
    import re

    text = path.read_text()
    # Strip comments (outside of quoted strings — good enough for our config)
    lines = []
    for raw_line in text.splitlines():
        stripped = raw_line.split("#")[0].rstrip()
        lines.append(stripped)

    result: dict = {}
    current_section: dict | None = None
    current_entity: dict | None = None
    current_attrs: dict | None = None

    i = 0
    while i < len(lines):
        line = lines[i]
        i += 1
        if not line.strip():
            continue

        indent = len(line) - len(line.lstrip())

        # Top-level key: value
        if indent == 0 and ":" in line:
            key, _, val = line.partition(":")
            key = key.strip()
            val = val.strip()
            if val:
                # Try to cast to int/float
                try:
                    result[key] = int(val)
                except ValueError:
                    try:
                        result[key] = float(val)
                    except ValueError:
                        result[key] = val
            else:
                result[key] = {}
                if key == "entities":
                    current_section = result[key]
            continue

        # Entity name under entities:
        if current_section is not None and indent == 2 and ":" in line:
            ename = line.strip().rstrip(":")
            current_entity = {}
            current_section[ename] = current_entity
            current_attrs = None
            continue

        if current_entity is not None and indent == 4 and ":" in line:
            key, _, val = line.strip().partition(":")
            key = key.strip()
            val = val.strip()
            if key == "attributes":
                current_attrs = {}
                current_entity["attributes"] = current_attrs
            elif key == "volume":
                current_entity[key] = int(val)
            elif key == "parent":
                current_entity[key] = val
            continue

        # Attribute lines (indent >= 6)
        if current_attrs is not None and indent >= 6:
            # Parse:  attr_name: { ... }
            m = re.match(r"\s+(\w+):\s*\{(.*)\}", line.strip())
            if m:
                attr_name = m.group(1)
                inner = m.group(2)
                # Minimal inline dict parse
                attr_def: dict = {}
                for part in _split_top_level(inner):
                    k2, _, v2 = part.partition(":")
                    k2 = k2.strip()
                    v2 = v2.strip().strip('"').strip("'")
                    # Handle inline lists like [a, b, c]
                    if v2.startswith("[") and v2.endswith("]"):
                        items = [x.strip().strip('"').strip("'") for x in v2[1:-1].split(",")]
                        # Try numeric conversion
                        converted = []
                        for item in items:
                            try:
                                converted.append(float(item))
                            except ValueError:
                                converted.append(item)
                        attr_def[k2] = converted
                    # Handle inline maps like { k: v, k: v }
                    elif v2.startswith("{") and v2.endswith("}"):
                        map_items = {}
                        for mp in v2[1:-1].split(","):
                            mk, _, mv = mp.partition(":")
                            map_items[mk.strip().strip('"').strip("'")] = mv.strip().strip('"').strip("'")
                        attr_def[k2] = map_items
                    else:
                        try:
                            attr_def[k2] = float(v2)
                            if attr_def[k2] == int(attr_def[k2]):
                                attr_def[k2] = int(attr_def[k2])
                        except ValueError:
                            attr_def[k2] = v2
                current_attrs[attr_name] = attr_def

    return result


def _split_top_level(s: str) -> list[str]:
    """Split a comma-separated string respecting nested brackets."""
    parts: list[str] = []
    depth = 0
    current: list[str] = []
    for ch in s:
        if ch in ("{", "["):
            depth += 1
            current.append(ch)
        elif ch in ("}", "]"):
            depth -= 1
            current.append(ch)
        elif ch == "," and depth == 0:
            parts.append("".join(current).strip())
            current = []
        else:
            current.append(ch)
    if current:
        parts.append("".join(current).strip())
    return parts


def load_config(config_path: Path) -> dict:
    """Load config.yaml using PyYAML if available, else minimal parser."""
    if yaml is not None:
        with open(config_path) as f:
            return yaml.safe_load(f)
    log.info("PyYAML not installed; using minimal built-in parser")
    return _minimal_yaml_load(config_path)


# ---------------------------------------------------------------------------
# Data generation
# ---------------------------------------------------------------------------

def _weighted_choice(rng: random.Random, values: list, weights: list):
    """Pick a value from *values* using *weights*."""
    return rng.choices(values, weights=weights, k=1)[0]


def _hex_string(rng: random.Random, length: int) -> str:
    """Generate a random hex string of *length* characters."""
    return "".join(rng.choices("0123456789ABCDEF", k=length))


def _offset_coord(
    lat: float, lng: float, distance_km: float, bearing_deg: float,
) -> tuple[float, float]:
    """Return (lat, lng) offset from a point by *distance_km* at *bearing_deg*.

    Uses simple flat-Earth approximation (1 deg lat ≈ 111 km).
    Accurate enough for offsets up to ~10 km at non-polar latitudes.
    """
    bearing_rad = math.radians(bearing_deg)
    dlat = (distance_km / 111.0) * math.cos(bearing_rad)
    # longitude degree shrinks with latitude
    dlng = (distance_km / (111.0 * math.cos(math.radians(lat)))) * math.sin(bearing_rad)
    return round(lat + dlat, 6), round(lng + dlng, 6)


def generate_sites(rng: random.Random, cfg: dict, pools: dict, region: dict) -> list[dict]:
    """Generate site records."""
    entity_cfg = cfg["entities"]["site"]
    volume = entity_cfg["volume"]
    site_names = region["site_names"]
    lat_min, lat_max = region["latitude"]["min"], region["latitude"]["max"]
    lng_min, lng_max = region["longitude"]["min"], region["longitude"]["max"]
    statuses, status_weights = get_enum_with_weights(
        entity_cfg, "status", pools["site_statuses"], pools["site_status_weights"],
    )
    sites = []
    for seq in range(1, volume + 1):
        site = {
            "site_id": f"SITE-{seq:04d}",
            "site_name": site_names[(seq - 1) % len(site_names)],
            "latitude": round(rng.uniform(lat_min, lat_max), 6),
            "longitude": round(rng.uniform(lng_min, lng_max), 6),
            "status": _weighted_choice(rng, statuses, status_weights),
        }
        sites.append(site)
    log.info("Generated %d sites", len(sites))
    return sites


def generate_racks(
    rng: random.Random, sites: list[dict], olts_per_site: dict[str, int], pools: dict,
) -> list[dict]:
    """Generate rack records for each site.

    Each site gets enough racks to house its OLTs (42U standard racks with 1U
    spacing between devices). OLTs are assigned to racks round-robin within
    their site.
    """
    olt_vendors = pools["olt_vendors"]
    max_u = max(v.get("u_height", 6) for v in olt_vendors.values())
    # How many OLTs fit per rack: (42U - 2U top/bottom margin) / (max_u_height + 1U gap)
    max_olts_per_rack = max(1, (42 - 2) // (max_u + 1))

    racks = []
    for site in sites:
        site_id = site["site_id"]
        n_olts = olts_per_site.get(site_id, 0)
        n_racks = max(1, math.ceil(n_olts / max_olts_per_rack))
        for r_idx in range(1, n_racks + 1):
            racks.append({
                "rack_id": f"RACK-{site_id}-{r_idx:02d}",
                "parent_site_id": site_id,
                "rack_name": f"R{r_idx:02d}",
                "u_height": 42,
            })
    log.info("Generated %d racks", len(racks))
    return racks


def generate_olts(
    rng: random.Random, cfg: dict, sites: list[dict], pools: dict,
    racks: list[dict] | None = None,
) -> list[dict]:
    """Generate OLT records with round-robin site assignment.

    Each OLT gets lat/lng coordinates near its parent site (±50m jitter).
    When racks are provided, each OLT is assigned to a rack with a U position.
    """
    entity_cfg = cfg["entities"]["olt"]
    volume = entity_cfg["volume"]
    olt_vendors = pools["olt_vendors"]
    vendors = list(olt_vendors.keys())
    vendor_weights = pools["olt_vendor_weights"]
    statuses, status_weights = get_enum_with_weights(
        entity_cfg, "status", pools["olt_statuses"], pools["olt_status_weights"],
    )
    # Build site coordinate lookup
    site_coords = {s["site_id"]: (float(s["latitude"]), float(s["longitude"])) for s in sites}

    # Build rack assignment structures
    site_racks: dict[str, list[dict]] = {}  # site_id → list of racks
    rack_next_u: dict[str, int] = {}  # rack_id → next available U position (bottom-up)
    if racks:
        for rack in racks:
            site_racks.setdefault(rack["parent_site_id"], []).append(rack)
            rack_next_u[rack["rack_id"]] = 1  # start from U1 (bottom)

    # Track per-site OLT counter for round-robin rack assignment
    site_olt_counter: dict[str, int] = {}

    olts = []
    for seq in range(1, volume + 1):
        # Round-robin parent assignment with jitter
        parent_idx = (seq - 1) % len(sites)
        parent = sites[parent_idx]
        vendor = _weighted_choice(rng, vendors, vendor_weights)
        vinfo = olt_vendors[vendor]
        u_height = vinfo.get("u_height", 6)
        # OLT at CO site with ±50m jitter
        slat, slng = site_coords[parent["site_id"]]
        lat, lng = _offset_coord(
            slat, slng,
            distance_km=rng.uniform(0.01, 0.05),
            bearing_deg=rng.uniform(0, 360),
        )
        olt = {
            "olt_id": f"OLT-{parent['site_id']}-{seq:02d}",
            "parent_site_id": parent["site_id"],
            "vendor": vendor,
            "model": vinfo["model"],
            "serial": f"{vinfo['serial_prefix']}{_hex_string(rng, 8)}",
            "software": vinfo["software"],
            "status": _weighted_choice(rng, statuses, status_weights),
            "latitude": lat,
            "longitude": lng,
            "rack_id": "",
            "rack_position": "",
        }

        # Assign to rack if racks are available for this site
        site_id = parent["site_id"]
        available_racks = site_racks.get(site_id, [])
        if available_racks:
            idx = site_olt_counter.get(site_id, 0)
            site_olt_counter[site_id] = idx + 1
            rack = available_racks[idx % len(available_racks)]
            rack_id = rack["rack_id"]
            position = rack_next_u[rack_id]
            olt["rack_id"] = rack_id
            olt["rack_position"] = str(position)
            # Advance: device height + 1U gap
            rack_next_u[rack_id] = position + u_height + 1

        olts.append(olt)
    log.info("Generated %d OLTs", len(olts))
    return olts


def generate_slots(rng: random.Random, olts: list[dict], pools: dict, depth: dict) -> list[dict]:
    """Generate slot records for each OLT with configurable service slot count."""
    olt_chassis = pools["olt_chassis"]
    slot_min, slot_max = depth.get("slots_per_olt", [2, 4])
    slots = []
    slot_seq = 0
    for olt in olts:
        vendor = olt["vendor"]
        chassis = olt_chassis[vendor]
        num_service = rng.randint(slot_min, min(slot_max, len(chassis["service_slots"])))
        service_positions = sorted(rng.sample(chassis["service_slots"], num_service))
        # Pick 1 control slot
        control_position = rng.choice(chassis["control_slots"])

        for pos in service_positions:
            slot_seq += 1
            slots.append({
                "slot_id": f"SLOT-{olt['olt_id']}-{pos:02d}",
                "parent_olt_id": olt["olt_id"],
                "slot_number": pos,
                "slot_type": "service",
            })
        slot_seq += 1
        slots.append({
            "slot_id": f"SLOT-{olt['olt_id']}-{control_position:02d}",
            "parent_olt_id": olt["olt_id"],
            "slot_number": control_position,
            "slot_type": "control",
        })
    log.info("Generated %d slots", len(slots))
    return slots


def generate_line_cards(rng: random.Random, olts: list[dict], slots: list[dict], pools: dict) -> list[dict]:
    """Generate line card records — one per equipped slot."""
    olt_chassis = pools["olt_chassis"]
    olt_vendors = pools["olt_vendors"]
    # Build vendor lookup from OLTs
    olt_vendor: dict[str, str] = {olt["olt_id"]: olt["vendor"] for olt in olts}
    cards = []
    for slot in slots:
        vendor = olt_vendor[slot["parent_olt_id"]]
        chassis = olt_chassis[vendor]

        if slot["slot_type"] == "service":
            gpon_cards = chassis["gpon_cards"]
            models = [c["model"] for c in gpon_cards]
            weights = [c["weight"] for c in gpon_cards]
            card_model = _weighted_choice(rng, models, weights)
            port_count = next(c["ports"] for c in gpon_cards if c["model"] == card_model)
            card_type = "gpon"
        else:
            ctrl = chassis["control_card"]
            card_model = ctrl["model"]
            port_count = ctrl["uplink_ports"]
            card_type = "control"

        prefix = olt_vendors[vendor]["serial_prefix"]
        cards.append({
            "card_id": f"CARD-{slot['slot_id']}",
            "parent_slot_id": slot["slot_id"],
            "parent_olt_id": slot["parent_olt_id"],
            "card_model": card_model,
            "port_count": port_count,
            "card_type": card_type,
            "slot_number": slot["slot_number"],
            "serial": f"{prefix}{_hex_string(rng, 8)}",
        })
    log.info("Generated %d line cards", len(cards))
    return cards


def generate_splitters(
    rng: random.Random, cfg: dict, olts: list[dict], line_cards: list[dict],
    pools: dict, sites: list[dict],
) -> list[dict]:
    """Generate splitter records with port assignment from GPON line cards.

    Each splitter gets a unique port on a GPON line card using 0/slot/port naming.
    Splitters are placed 0.5–3 km from their parent site at a random bearing.
    """
    entity_cfg = cfg["entities"]["splitter"]
    volume = entity_cfg["volume"]

    # Build site coordinate lookup via OLT → site
    site_coords = {s["site_id"]: (float(s["latitude"]), float(s["longitude"])) for s in sites}
    olt_site = {o["olt_id"]: o["parent_site_id"] for o in olts}

    # Build available port pool per OLT from GPON line cards
    # Each entry: (card_id, slot_number, port_index)
    olt_port_pool: dict[str, list[tuple[str, int, int]]] = {}
    for card in line_cards:
        if card["card_type"] != "gpon":
            continue
        olt_id = card["parent_olt_id"]
        if olt_id not in olt_port_pool:
            olt_port_pool[olt_id] = []
        for port_idx in range(1, card["port_count"] + 1):
            olt_port_pool[olt_id].append((card["card_id"], card["slot_number"], port_idx))

    # Track next available port per OLT
    olt_port_cursor: dict[str, int] = {olt["olt_id"]: 0 for olt in olts}

    splitters = []
    for seq in range(1, volume + 1):
        parent_idx = (seq - 1) % len(olts)
        parent = olts[parent_idx]
        olt_id = parent["olt_id"]

        # Get next port from pool (wrap around if needed)
        pool = olt_port_pool.get(olt_id, [])
        if not pool:
            log.warning("No GPON ports available for OLT %s", olt_id)
            continue
        cursor = olt_port_cursor[olt_id]
        card_id, slot_num, port_idx = pool[cursor % len(pool)]
        olt_port_cursor[olt_id] = cursor + 1

        port_name = f"0/{slot_num}/{port_idx}"

        ratios, ratio_weights = get_enum_with_weights(
            entity_cfg, "split_ratio", pools["split_ratios"], pools["split_ratio_weights"],
        )

        # Place splitter 0.5–3 km from parent site center
        site_id = olt_site.get(olt_id, "")
        slat, slng = site_coords.get(site_id, (0.0, 0.0))
        lat, lng = _offset_coord(
            slat, slng,
            distance_km=rng.uniform(0.5, 3.0),
            bearing_deg=rng.uniform(0, 360),
        )

        splitter = {
            "splitter_id": f"SPL-{olt_id}-{seq:02d}",
            "parent_olt_id": olt_id,
            "parent_splitter_id": "",
            "split_ratio": _weighted_choice(rng, ratios, ratio_weights),
            "olt_port": port_name,
            "olt_card_id": card_id,
            "location": f"Cab-{parent['parent_site_id']}-R{seq:02d}",
            "cascade_level": 1,
            "latitude": lat,
            "longitude": lng,
        }
        splitters.append(splitter)
    log.info("Generated %d splitters", len(splitters))
    return splitters


def generate_cascade_splitters(
    rng: random.Random, l1_splitters: list[dict], depth: dict
) -> list[dict]:
    """Generate level-2 cascade splitters (SPL1 → SPL2).

    A fraction of L1 splitters (controlled by depth.cascade_ratio) get L2 children.
    Each L2 splitter has a 1:8 ratio and connects to the L1 splitter's output.
    L2 splitters are placed 0.2–1 km from their parent L1 splitter.
    """
    cascade_levels = depth.get("splitter_cascade_levels", 1)
    if cascade_levels < 2:
        return []

    cascade_ratio = depth.get("cascade_ratio", 0.4)
    l2_splitters = []
    l2_seq = 0

    for spl in l1_splitters:
        if rng.random() >= cascade_ratio:
            continue
        parent_lat = float(spl.get("latitude", 0))
        parent_lng = float(spl.get("longitude", 0))
        # Each L1 splitter that cascades gets 2 L2 children
        for _ in range(2):
            l2_seq += 1
            lat, lng = _offset_coord(
                parent_lat, parent_lng,
                distance_km=rng.uniform(0.2, 1.0),
                bearing_deg=rng.uniform(0, 360),
            )
            l2_splitters.append({
                "splitter_id": f"SPL2-{spl['splitter_id']}-{l2_seq:03d}",
                "parent_splitter_id": spl["splitter_id"],
                "parent_olt_id": spl["parent_olt_id"],
                "split_ratio": "1:8",
                "olt_port": spl["olt_port"],
                "olt_card_id": spl["olt_card_id"],
                "location": f"{spl['location']}-L2-{l2_seq:03d}",
                "cascade_level": 2,
                "latitude": lat,
                "longitude": lng,
            })

    log.info("Generated %d L2 cascade splitters", len(l2_splitters))
    return l2_splitters


def generate_sfp_transceivers(
    rng: random.Random, splitters: list[dict], pools: dict
) -> list[dict]:
    """Generate SFP transceivers for connected GPON ports (one per splitter)."""
    sfps = []
    # Group splitters by card_id + port to avoid duplicates
    seen_ports: set[str] = set()
    for spl in splitters:
        card_id = spl["olt_card_id"]
        port_name = spl["olt_port"]
        port_key = f"{card_id}:{port_name}"
        if port_key in seen_ports:
            continue
        seen_ports.add(port_key)

        # Extract port index from 0/slot/port
        port_index = int(port_name.split("/")[2])
        sfp_class = _weighted_choice(rng, pools["sfp_classes"], pools["sfp_class_weights"])
        sfps.append({
            "sfp_id": f"SFP-{card_id}-{port_index:02d}",
            "parent_card_id": card_id,
            "sfp_class": sfp_class,
            "wavelength": pools["sfp_wavelength"],
            "port_index": port_index,
            "port_name": port_name,
        })
    log.info("Generated %d SFP transceivers", len(sfps))
    return sfps


def generate_onts(rng: random.Random, cfg: dict, splitters: list[dict], pools: dict) -> list[dict]:
    """Generate ONT records with round-robin splitter assignment.

    Each ONT gets lat/lng coordinates 0.1–1 km from its parent splitter.
    """
    entity_cfg = cfg["entities"]["ont"]
    volume = entity_cfg["volume"]
    ont_models = pools["ont_models"]
    ont_model_names = list(ont_models.keys())
    ont_model_weights = pools["ont_model_weights"]
    statuses, status_weights = get_enum_with_weights(
        entity_cfg, "status", pools["ont_statuses"], pools["ont_status_weights"],
    )
    # Build splitter coordinate lookup
    spl_coords = {}
    for s in splitters:
        if s.get("latitude") and s.get("longitude"):
            spl_coords[s["splitter_id"]] = (float(s["latitude"]), float(s["longitude"]))

    onts = []
    for seq in range(1, volume + 1):
        parent_idx = (seq - 1) % len(splitters)
        parent = splitters[parent_idx]
        model_name = _weighted_choice(rng, ont_model_names, ont_model_weights)
        minfo = ont_models[model_name]
        # Place ONT 0.1–1 km from parent splitter
        plat, plng = spl_coords.get(parent["splitter_id"], (0.0, 0.0))
        lat, lng = _offset_coord(
            plat, plng,
            distance_km=rng.uniform(0.1, 1.0),
            bearing_deg=rng.uniform(0, 360),
        )
        ont = {
            "ont_id": f"ONT-{seq:06d}",
            "parent_splitter_id": parent["splitter_id"],
            "serial_number": f"{minfo['serial_prefix']}{_hex_string(rng, 8)}",
            "ont_model": model_name,
            "vendor": minfo["vendor"],
            "customer_ref": f"CUST-{_hex_string(rng, 12)}",
            "status": _weighted_choice(rng, statuses, status_weights),
            "latitude": lat,
            "longitude": lng,
        }
        onts.append(ont)
    log.info("Generated %d ONTs", len(onts))
    return onts


def generate_connections(
    olts: list[dict], l1_splitters: list[dict], l2_splitters: list[dict],
    onts: list[dict], pools: dict,
) -> list[dict]:
    """Generate fiber connection records.

    Handles both 1-level (OLT→SPL→ONT) and 2-level (OLT→SPL1→SPL2→ONT) topologies.

    Port naming:
    - OLT side: 0/{slot}/{port} (shelf/slot/port naming from line cards)
    - Splitter input: ``input`` (one per splitter)
    - Splitter output: ``output-{n}`` (numbered per child)
    - ONT side: ``pon`` (one per ONT)
    """
    connections = []
    conn_seq = 0

    # OLT ↔ L1 splitter connections
    for spl in l1_splitters:
        conn_seq += 1
        connections.append({
            "connection_id": f"CONN-{conn_seq:06d}",
            "a_endpoint_type": "olt",
            "a_endpoint_id": spl["parent_olt_id"],
            "a_port": spl["olt_port"],
            "b_endpoint_type": "splitter",
            "b_endpoint_id": spl["splitter_id"],
            "b_port": "input",
            "fiber_type": pools["fiber_types"]["olt_to_splitter"],
        })

    # L1 splitter ↔ L2 splitter connections
    l1_output_counter: dict[str, int] = {}
    for spl2 in l2_splitters:
        conn_seq += 1
        parent_id = spl2["parent_splitter_id"]
        port_num = l1_output_counter.get(parent_id, 0) + 1
        l1_output_counter[parent_id] = port_num
        connections.append({
            "connection_id": f"CONN-{conn_seq:06d}",
            "a_endpoint_type": "splitter",
            "a_endpoint_id": parent_id,
            "a_port": f"output-{port_num}",
            "b_endpoint_type": "splitter",
            "b_endpoint_id": spl2["splitter_id"],
            "b_port": "input",
            "fiber_type": pools["fiber_types"]["olt_to_splitter"],
        })

    # Splitter ↔ ONT connections (from whichever splitter the ONT is parented to)
    splitter_output_counter: dict[str, int] = {}
    for ont in onts:
        conn_seq += 1
        spl_id = ont["parent_splitter_id"]
        # Start numbering after any L2 children that already used output ports
        port_num = splitter_output_counter.get(spl_id, l1_output_counter.get(spl_id, 0)) + 1
        splitter_output_counter[spl_id] = port_num
        connections.append({
            "connection_id": f"CONN-{conn_seq:06d}",
            "a_endpoint_type": "splitter",
            "a_endpoint_id": spl_id,
            "a_port": f"output-{port_num}",
            "b_endpoint_type": "ont",
            "b_endpoint_id": ont["ont_id"],
            "b_port": "pon",
            "fiber_type": pools["fiber_types"]["splitter_to_ont"],
        })

    log.info("Generated %d connections", len(connections))
    return connections


# ---------------------------------------------------------------------------
# Service inventory generators (CFS/RFS)
# ---------------------------------------------------------------------------

def generate_subscribers(
    rng: random.Random, onts: list[dict], pools: dict,
) -> list[dict]:
    """Generate one subscriber per ONT."""
    first_names = pools["subscriber_first_names"]
    last_names = pools["subscriber_last_names"]
    subscribers = []
    for seq, ont in enumerate(onts, 1):
        fname = rng.choice(first_names)
        lname = rng.choice(last_names)
        subscribers.append({
            "subscriber_id": f"SUB-{seq:06d}",
            "ont_id": ont["ont_id"],
            "customer_name": f"{fname} {lname}",
            "address": f"ul. {lname} {rng.randint(1, 200)}, {ont.get('parent_splitter_id', '').split('-')[2] if '-' in ont.get('parent_splitter_id', '') else 'City'}",
            "contract_start": f"2025-{rng.randint(1,12):02d}-{rng.randint(1,28):02d}",
            "status": "ACTIVE" if ont["status"] == "ACTIVE" else "SUSPENDED",
        })
    log.info("Generated %d subscribers", len(subscribers))
    return subscribers


def generate_services_cfs(
    rng: random.Random, subscribers: list[dict], pools: dict,
) -> list[dict]:
    """Generate one CFS (customer-facing service) per subscriber."""
    tiers = pools["service_tiers"]
    tier_weights = pools["service_tier_weights"]
    services = []
    for seq, sub in enumerate(subscribers, 1):
        tier = _weighted_choice(rng, tiers, tier_weights)
        services.append({
            "cfs_id": f"CFS-{seq:06d}",
            "subscriber_id": sub["subscriber_id"],
            "service_tier": tier["name"],
            "bandwidth_down_mbps": tier["down"],
            "bandwidth_up_mbps": tier["up"],
            "status": sub["status"],
        })
    log.info("Generated %d CFS records", len(services))
    return services


def generate_services_rfs(
    rng: random.Random, cfs_list: list[dict], subscribers: list[dict],
    onts: list[dict], splitters: list[dict], olts: list[dict],
) -> list[dict]:
    """Generate one RFS (resource-facing service) per CFS.

    Each RFS captures the PON path and VLAN assignment.
    """
    # Build lookup maps
    sub_ont = {s["subscriber_id"]: s["ont_id"] for s in subscribers}
    ont_spl = {o["ont_id"]: o["parent_splitter_id"] for o in onts}
    spl_olt = {s["splitter_id"]: s["parent_olt_id"] for s in splitters}

    services = []
    for seq, cfs in enumerate(cfs_list, 1):
        ont_id = sub_ont.get(cfs["subscriber_id"], "")
        spl_id = ont_spl.get(ont_id, "")
        olt_id = spl_olt.get(spl_id, "")
        pon_path = f"{olt_id}→{spl_id}→{ont_id}"
        services.append({
            "rfs_id": f"RFS-{seq:06d}",
            "cfs_id": cfs["cfs_id"],
            "ont_id": ont_id,
            "vlan_id": 100 + (seq % 4000),
            "pon_path": pon_path,
            "status": cfs["status"],
        })
    log.info("Generated %d RFS records", len(services))
    return services


def generate_service_resource_links(
    rfs_list: list[dict], onts: list[dict], splitters: list[dict],
    connections: list[dict],
) -> list[dict]:
    """Generate resource links: each RFS → ONT, OLT port, splitter, fibers."""
    ont_spl = {o["ont_id"]: o["parent_splitter_id"] for o in onts}
    spl_olt = {s["splitter_id"]: s["parent_olt_id"] for s in splitters}
    # Find connection IDs involving each ONT or splitter
    endpoint_conns: dict[str, list[str]] = {}
    for c in connections:
        for ep in (c["a_endpoint_id"], c["b_endpoint_id"]):
            endpoint_conns.setdefault(ep, []).append(c["connection_id"])

    links = []
    link_seq = 0
    for rfs in rfs_list:
        ont_id = rfs["ont_id"]
        spl_id = ont_spl.get(ont_id, "")
        olt_id = spl_olt.get(spl_id, "")

        for resource_type, resource_id in [
            ("ont", ont_id),
            ("splitter", spl_id),
            ("olt", olt_id),
        ]:
            if resource_id:
                link_seq += 1
                links.append({
                    "link_id": f"SRL-{link_seq:06d}",
                    "rfs_id": rfs["rfs_id"],
                    "resource_type": resource_type,
                    "resource_id": resource_id,
                })
        # Add fiber connections touching the ONT
        for conn_id in endpoint_conns.get(ont_id, []):
            link_seq += 1
            links.append({
                "link_id": f"SRL-{link_seq:06d}",
                "rfs_id": rfs["rfs_id"],
                "resource_type": "connection",
                "resource_id": conn_id,
            })

    log.info("Generated %d service-resource links", len(links))
    return links


# ---------------------------------------------------------------------------
# Output helpers
# ---------------------------------------------------------------------------

def write_csv(filepath: Path, rows: list[dict]) -> int:
    """Write a list of dicts to a CSV file. Returns row count."""
    if not rows:
        return 0
    filepath.parent.mkdir(parents=True, exist_ok=True)
    with open(filepath, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=rows[0].keys())
        writer.writeheader()
        writer.writerows(rows)
    log.info("Wrote %d rows to %s", len(rows), filepath)
    return len(rows)


def sha256_file(filepath: Path) -> str:
    """Compute SHA-256 hex digest of a file."""
    h = hashlib.sha256()
    with open(filepath, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def write_manifest(output_dir: Path, file_counts: dict[str, int]) -> None:
    """Write manifest.json with file list, counts, and checksums."""
    manifest = {"files": {}}
    for filename, count in file_counts.items():
        filepath = output_dir / filename
        manifest["files"][filename] = {
            "rows": count,
            "sha256": sha256_file(filepath),
        }
    manifest["total_rows"] = sum(file_counts.values())
    manifest_path = output_dir / "manifest.json"
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)
    log.info("Wrote manifest to %s", manifest_path)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate synthetic GPON inventory data as CSV files."
    )
    parser.add_argument(
        "--config", default="config.yaml",
        help="Path to config YAML (default: config.yaml)",
    )
    parser.add_argument(
        "--output-dir", default=None,
        help="Output directory (overrides config output_dir)",
    )
    parser.add_argument(
        "--seed", type=int, default=None,
        help="Random seed (overrides config seed)",
    )
    parser.add_argument(
        "--include-services", action="store_true",
        help="Generate subscriber and service inventory CSVs (CFS/RFS).",
    )
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )

    config_path = Path(args.config)
    if not config_path.exists():
        log.error("Config file not found: %s", config_path)
        sys.exit(1)

    cfg = load_config(config_path)
    seed = args.seed if args.seed is not None else cfg.get("seed", 42)
    rng = random.Random(seed)
    log.info("Using seed: %d", seed)

    pools = resolve_defaults(cfg)
    depth = resolve_depth(cfg)
    complexity = resolve_complexity(cfg, pools)
    region = resolve_region(cfg)
    log.info("Region: %s", region["name"])
    log.info("Depth: cascade_levels=%d, slots_per_olt=%s",
             depth["splitter_cascade_levels"], depth["slots_per_olt"])
    log.info("Complexity: vendor_mode=%s, ont_variety=%s, failure_rate=%d%%",
             complexity["vendor_mode"], complexity["ont_model_variety"],
             complexity["failure_rate_percent"])

    output_dir = Path(args.output_dir) if args.output_dir else Path(cfg.get("output_dir", "./output/"))
    output_dir.mkdir(parents=True, exist_ok=True)

    # Generate in dependency order
    sites = generate_sites(rng, cfg, pools, region)

    # Compute OLTs-per-site for rack sizing (round-robin distribution)
    olt_volume = cfg["entities"]["olt"]["volume"]
    olts_per_site: dict[str, int] = {}
    for seq in range(1, olt_volume + 1):
        site = sites[(seq - 1) % len(sites)]
        olts_per_site[site["site_id"]] = olts_per_site.get(site["site_id"], 0) + 1
    racks = generate_racks(rng, sites, olts_per_site, pools)
    olts = generate_olts(rng, cfg, sites, pools, racks)
    slots = generate_slots(rng, olts, pools, depth)
    line_cards = generate_line_cards(rng, olts, slots, pools)
    l1_splitters = generate_splitters(rng, cfg, olts, line_cards, pools, sites)
    l2_splitters = generate_cascade_splitters(rng, l1_splitters, depth)
    sfp_transceivers = generate_sfp_transceivers(rng, l1_splitters, pools)

    # ONTs parent to L2 splitters if available, otherwise L1
    all_splitters = l1_splitters + l2_splitters
    onts = generate_onts(rng, cfg, all_splitters, pools)
    connections = generate_connections(olts, l1_splitters, l2_splitters, onts, pools)

    # Write CSVs
    file_counts = {}
    file_counts["sites.csv"] = write_csv(output_dir / "sites.csv", sites)
    file_counts["racks.csv"] = write_csv(output_dir / "racks.csv", racks)
    file_counts["olts.csv"] = write_csv(output_dir / "olts.csv", olts)
    file_counts["slots.csv"] = write_csv(output_dir / "slots.csv", slots)
    file_counts["line_cards.csv"] = write_csv(output_dir / "line_cards.csv", line_cards)
    file_counts["splitters.csv"] = write_csv(output_dir / "splitters.csv", all_splitters)
    file_counts["sfp_transceivers.csv"] = write_csv(output_dir / "sfp_transceivers.csv", sfp_transceivers)
    file_counts["onts.csv"] = write_csv(output_dir / "onts.csv", onts)
    file_counts["connections.csv"] = write_csv(output_dir / "connections.csv", connections)

    # Generate service inventory CSVs (opt-in)
    if args.include_services:
        from value_pools import (
            SERVICE_TIERS, SERVICE_TIER_WEIGHTS,
            SUBSCRIBER_FIRST_NAMES, SUBSCRIBER_LAST_NAMES,
        )
        svc_pools = {
            "subscriber_first_names": SUBSCRIBER_FIRST_NAMES,
            "subscriber_last_names": SUBSCRIBER_LAST_NAMES,
            "service_tiers": SERVICE_TIERS,
            "service_tier_weights": SERVICE_TIER_WEIGHTS,
        }
        subscribers = generate_subscribers(rng, onts, svc_pools)
        cfs_list = generate_services_cfs(rng, subscribers, svc_pools)
        rfs_list = generate_services_rfs(
            rng, cfs_list, subscribers, onts, all_splitters, olts,
        )
        srl_list = generate_service_resource_links(
            rfs_list, onts, all_splitters, connections,
        )
        file_counts["subscribers.csv"] = write_csv(output_dir / "subscribers.csv", subscribers)
        file_counts["services_cfs.csv"] = write_csv(output_dir / "services_cfs.csv", cfs_list)
        file_counts["services_rfs.csv"] = write_csv(output_dir / "services_rfs.csv", rfs_list)
        file_counts["service_resource_links.csv"] = write_csv(output_dir / "service_resource_links.csv", srl_list)

    # Write manifest
    write_manifest(output_dir, file_counts)

    total = sum(file_counts.values())
    log.info("Generation complete: %d total rows in %d files", total, len(file_counts))
    print(f"\nDone. {total} rows written to {output_dir}/")
    for fname, count in file_counts.items():
        print(f"  {fname}: {count} rows")


if __name__ == "__main__":
    main()
