# =============================================================================
# value_pools.py
# Generated by: synthetic-data-generator | Date: 2026-02-19
# Purpose: Realistic GPON vendor/model/status constants for synthetic data.
# Assumptions: GPON access network domain; vendors Huawei, Nokia, ZTE.
# =============================================================================

"""Constant pools for GPON synthetic data generation.

Provides vendor data, ONT models, serial prefixes, interface types,
and status distributions used by generate_synthetic_data.py.
"""

# ---------------------------------------------------------------------------
# OLT vendors and models
# ---------------------------------------------------------------------------

OLT_VENDORS = {
    "Huawei": {
        "model": "MA5800-X15",
        "serial_prefix": "HWTC",
        "port_counts": [8, 16],
        "software": "MA5800V800R021C00",
        "u_height": 6,
    },
    "Nokia": {
        "model": "ISAM-FX16",
        "serial_prefix": "ALCI",
        "port_counts": [8, 16],
        "software": "ISAM-R6.2.1",
        "u_height": 5,
    },
    "ZTE": {
        "model": "C600",
        "serial_prefix": "ZTEG",
        "port_counts": [8, 16],
        "software": "ZTE-V6.0.10P3",
        "u_height": 4,
    },
}

OLT_VENDOR_WEIGHTS = [0.5, 0.3, 0.2]  # Huawei, Nokia, ZTE

# ---------------------------------------------------------------------------
# ONT models
# ---------------------------------------------------------------------------

ONT_MODELS = {
    "HG8245H": {"vendor": "Huawei", "serial_prefix": "HWTC", "ports_lan": 4},
    "HG8546M": {"vendor": "Huawei", "serial_prefix": "HWTC", "ports_lan": 4},
    "F660": {"vendor": "ZTE", "serial_prefix": "ZTEG", "ports_lan": 4},
    "I-010G-Q": {"vendor": "Nokia", "serial_prefix": "ALCI", "ports_lan": 1},
}

ONT_MODEL_WEIGHTS = [0.35, 0.25, 0.25, 0.15]

# ---------------------------------------------------------------------------
# Splitter configurations
# ---------------------------------------------------------------------------

SPLIT_RATIOS = ["1:8", "1:16", "1:32"]
SPLIT_RATIO_WEIGHTS = [0.2, 0.5, 0.3]

# ---------------------------------------------------------------------------
# Status values and distributions
# ---------------------------------------------------------------------------

SITE_STATUSES = ["ACTIVE", "PLANNED"]
SITE_STATUS_WEIGHTS = [0.9, 0.1]

OLT_STATUSES = ["IN_SERVICE", "MAINTENANCE"]
OLT_STATUS_WEIGHTS = [0.95, 0.05]

ONT_STATUSES = ["ACTIVE", "SUSPENDED", "INACTIVE"]
ONT_STATUS_WEIGHTS = [0.85, 0.10, 0.05]

# ---------------------------------------------------------------------------
# Site name pools
# ---------------------------------------------------------------------------

SITE_NAMES = [
    "Prague Central CO",
    "Brno South CO",
    "Ostrava Main CO",
    "Plzen West CO",
    "Liberec North CO",
    "Olomouc East CO",
    "Ceske Budejovice CO",
    "Hradec Kralove CO",
    "Pardubice CO",
    "Zlin CO",
]

# ---------------------------------------------------------------------------
# NetBox-specific interface type constants
# ---------------------------------------------------------------------------

NETBOX_INTERFACE_TYPES = {
    "pon_uplink": "10gbase-x-sfpp",   # 10G SFP+ for PON uplink
    "gpon_port": "1000base-x-sfp",    # GPON SFP port on OLT
    "ont_lan": "1000base-t",          # GbE copper on ONT
    "ont_pon": "1000base-x-sfp",      # ONT PON port
}

# ---------------------------------------------------------------------------
# Connection types
# ---------------------------------------------------------------------------

FIBER_TYPES = {
    "olt_to_splitter": "smf",   # Single-mode fiber
    "splitter_to_ont": "smf",
}

# ---------------------------------------------------------------------------
# OLT chassis structure (slots, line cards, control cards)
# ---------------------------------------------------------------------------

OLT_CHASSIS = {
    "Huawei": {
        "service_slots": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        "control_slots": [16, 17],
        "gpon_cards": [
            {"model": "H901GPHF", "ports": 16, "weight": 0.5},
            {"model": "H901GPUF", "ports": 16, "weight": 0.3},
            {"model": "H901GPSF", "ports": 16, "weight": 0.2},
        ],
        "control_card": {"model": "H901MPLA", "uplink_ports": 4, "uplink_type": "10GE"},
    },
    "Nokia": {
        "service_slots": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
        "control_slots": [17, 18],
        "gpon_cards": [
            {"model": "FGLT-B", "ports": 16, "weight": 0.6},
            {"model": "NGLT-A", "ports": 8, "weight": 0.4},
        ],
        "control_card": {"model": "FANT-F", "uplink_ports": 4, "uplink_type": "10GE"},
    },
    "ZTE": {
        "service_slots": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        "control_slots": [16, 17],
        "gpon_cards": [
            {"model": "GFGL", "ports": 16, "weight": 0.5},
            {"model": "GFGN", "ports": 16, "weight": 0.5},
        ],
        "control_card": {"model": "SFUH", "uplink_ports": 4, "uplink_type": "10GE"},
    },
}

# ---------------------------------------------------------------------------
# SFP transceiver classes
# ---------------------------------------------------------------------------

SFP_CLASSES = ["B+", "C+", "C++"]
SFP_CLASS_WEIGHTS = [0.3, 0.5, 0.2]
SFP_WAVELENGTH = "1490/1310nm"  # Downstream/upstream for GPON

# ---------------------------------------------------------------------------
# Subscriber name pools (Czech)
# ---------------------------------------------------------------------------

SUBSCRIBER_FIRST_NAMES = [
    "Jan", "Petr", "Martin", "Tomáš", "Pavel", "Jiří", "Jaroslav", "Miroslav",
    "Karel", "Lukáš", "Eva", "Jana", "Marie", "Anna", "Hana", "Lenka",
    "Kateřina", "Petra", "Lucie", "Veronika",
]

SUBSCRIBER_LAST_NAMES = [
    "Novák", "Svoboda", "Novotný", "Dvořák", "Černý", "Procházka", "Kučera",
    "Veselý", "Horák", "Němec", "Marková", "Pospíšilová", "Pokorná",
    "Hájková", "Králová",
]

# ---------------------------------------------------------------------------
# Service tiers (CFS broadband offerings)
# ---------------------------------------------------------------------------

SERVICE_TIERS = [
    {"name": "GPON Basic 30/10",      "down": 30,   "up": 10},
    {"name": "GPON Standard 100/50",   "down": 100,  "up": 50},
    {"name": "GPON Premium 300/100",   "down": 300,  "up": 100},
    {"name": "GPON Ultra 1000/300",    "down": 1000, "up": 300},
]
SERVICE_TIER_WEIGHTS = [0.15, 0.40, 0.30, 0.15]
