# =============================================================================
# base_adapter.py
# Generated by: target-loader-adapter | Date: 2026-02-19
# Purpose: Abstract base class for target inventory system adapters.
# Assumptions: Extends adapter-base-sample.py with config-dict connect,
#              health_check, bulk_create, and create_connection methods.
# =============================================================================

"""Abstract adapter interface for loading data into target inventory systems.

Concrete implementations are provided for Kuwaiba (SOAP) and NetBox (REST).
"""

from abc import ABC, abstractmethod
from typing import Any


class BaseTargetAdapter(ABC):
    """Abstract adapter that separates load logic from target-system specifics."""

    @abstractmethod
    def connect(self, config: dict) -> None:
        """Establish an authenticated session using a config dictionary.

        Args:
            config: Connection parameters (host, port, credentials, etc.).
                    Format depends on the concrete adapter.
        """
        ...

    @abstractmethod
    def disconnect(self) -> None:
        """Close the session and release resources."""
        ...

    @abstractmethod
    def health_check(self) -> bool:
        """Verify that the target system is reachable and responding.

        Returns:
            True if the target is healthy, False otherwise.
        """
        ...

    @abstractmethod
    def setup_model(self, model_def: dict[str, Any]) -> dict[str, str]:
        """Ensure required classes, types, and schema elements exist.

        Args:
            model_def: Schema definition with classes, attributes, and hierarchy.

        Returns:
            Mapping of logical class names to target-system IDs.
        """
        ...

    @abstractmethod
    def create_object(
        self, class_name: str, parent_id: str, attributes: dict[str, Any]
    ) -> str:
        """Create a single inventory object in the target system.

        Returns:
            The target-system ID of the newly created object.
        """
        ...

    def bulk_create(
        self, class_name: str, objects: list[dict[str, Any]]
    ) -> list[str]:
        """Create multiple objects. Default: iterate create_object.

        Subclasses may override with native bulk APIs.

        Returns:
            List of target-system IDs for the created objects.
        """
        ids = []
        for obj in objects:
            parent_id = obj.pop("_parent_id", "")
            obj_id = self.create_object(class_name, parent_id, obj)
            ids.append(obj_id)
        return ids

    @abstractmethod
    def create_connection(
        self,
        a_endpoint_id: str,
        a_port: str,
        b_endpoint_id: str,
        b_port: str,
        connection_type: str,
    ) -> str:
        """Create a physical connection (fiber link) between two endpoints.

        Returns:
            The target-system ID of the connection.
        """
        ...

    def create_visualization(
        self,
        id_mapping: dict[str, str],  # noqa: ARG002
        site_rows: list[dict[str, Any]],  # noqa: ARG002
        connection_rows: list[dict[str, Any]],  # noqa: ARG002
        device_rows: dict[str, list[dict[str, Any]]] | None = None,  # noqa: ARG002
    ) -> None:
        """Create a visual representation of the loaded network.

        Optional. Subclasses may override to create topology views,
        geographic maps, or other visualizations in the target system.

        Args:
            id_mapping: source_id → target_id for all created objects.
            site_rows: Parsed rows from sites.csv.
            connection_rows: Parsed rows from connections.csv.
            device_rows: Optional dict of entity_type → CSV rows with
                per-device lat/lng for geographic placement.
        """

    @abstractmethod
    def verify_load(self, class_name: str, expected_count: int) -> bool:
        """Verify that the expected number of objects exist in the target.

        Returns:
            True if counts match within tolerance, False otherwise.
        """
        ...
