#!/usr/bin/env python3
# =============================================================================
# kuwaiba_adapter.py
# Generated by: target-loader-adapter | Date: 2026-02-19
# Purpose: Kuwaiba SOAP adapter for loading GPON inventory data.
# Assumptions: Kuwaiba 2.1.1, zeep library, SOAP on localhost:8081.
# =============================================================================

"""Kuwaiba SOAP adapter using zeep.

Loads GPON entities into Kuwaiba's containment hierarchy via the
KuwaibaService SOAP API. Uses the standard telecom physical hierarchy:

    Country("GPON Demo") → City → Building → Room → Rack → OLT → Slot → Board → Port
    City → FiberSplitter / OpticalNetworkTerminal  (field-deployed)
"""

import logging
import math
import threading
import time
import uuid
from typing import Any

from base_adapter import BaseTargetAdapter

log = logging.getLogger(__name__)


class KuwaibaAdapter(BaseTargetAdapter):
    """Concrete adapter for Kuwaiba 2.1.1 SOAP API via zeep."""

    def __init__(self) -> None:
        self._client = None
        self._service = None
        self._session_id: str = ""
        self._config: dict = {}
        self._class_cache: dict[str, str] = {}  # entity_type → Kuwaiba class
        self._session_ts: float = 0.0
        self._session_ttl: float = 600.0  # 10 minutes
        self._country_oid: str = ""  # Root Country for all demo Cities
        # Track which City OID each device belongs to (for flattened containment)
        self._device_city_map: dict[str, str] = {}  # source_id → city_oid
        # Track port OIDs: "device_oid:port_name" → port_oid
        self._port_map: dict[str, str] = {}
        # Track slot → OLT mapping for port key resolution
        self._slot_olt_map: dict[str, str] = {}  # slot_oid → olt_oid
        # Track card → slot mapping for containment
        self._card_slot_map: dict[str, str] = {}  # card_oid → slot_oid
        # Track Building→Room chain per City for rack creation
        self._city_room_map: dict[str, str] = {}  # city_oid → room_oid
        # Track CSV rack_id → Kuwaiba rack OID
        self._rack_map: dict[str, str] = {}  # csv_rack_id → rack_oid
        self._lock = threading.Lock()  # protects mutable maps and session refresh

    # -- connection lifecycle ------------------------------------------------

    def connect(self, config: dict) -> None:
        """Establish a SOAP session with Kuwaiba.

        Args:
            config: Must contain wsdl_url, username, password.
        """
        try:
            from zeep import Client  # type: ignore[import-untyped]
        except ImportError:
            raise ImportError(
                "zeep is required for Kuwaiba adapter. "
                "Install with: pip install zeep"
            )

        self._config = config
        wsdl_url = config["wsdl_url"]
        log.info("Connecting to Kuwaiba WSDL: %s", wsdl_url)
        self._client = Client(wsdl_url)
        self._service = self._client.service
        self._create_session()

    def _create_session(self) -> None:
        """Create an authenticated session.

        Kuwaiba 2.1 createSession requires (username, password, sessionType).
        sessionType: 0=desktop, 1=web, 2=ws (web service).
        Returns a remoteSession object with a .sessionId attribute.
        """
        username = self._config["username"]
        password = self._config["password"]
        result = self._service.createSession(username, password, 2)
        self._session_id = result.sessionId
        self._session_ts = time.time()
        log.info("Kuwaiba session created: %s...", self._session_id[:16])

    def _ensure_session(self) -> None:
        """Refresh the session if it's close to expiry."""
        with self._lock:
            if time.time() - self._session_ts > self._session_ttl:
                log.info("Session approaching TTL, refreshing...")
                try:
                    self._service.closeSession(self._session_id)
                except Exception:
                    pass
                self._create_session()

    def disconnect(self) -> None:
        """Close the SOAP session."""
        if self._service and self._session_id:
            try:
                self._service.closeSession(self._session_id)
                log.info("Kuwaiba session closed")
            except Exception as e:
                log.warning("Error closing session: %s", e)
        self._session_id = ""

    # -- health check --------------------------------------------------------

    def health_check(self) -> bool:
        """Verify Kuwaiba is reachable by attempting a session create."""
        try:
            if not self._service:
                return False
            self._ensure_session()
            return bool(self._session_id)
        except Exception as e:
            log.error("Kuwaiba health check failed: %s", e)
            return False

    # -- model setup ---------------------------------------------------------

    def setup_model(self, model_def: dict[str, Any]) -> dict[str, str]:
        """Ensure containment rules, root Country, and vendor list types exist.

        1. Adds containment rules for: City→Building→Room→Rack→OLT,
           City→FiberSplitter/ONT, OLT→Slot→Board→Port.
        2. Creates a root "GPON Demo" Country under DummyRoot.
        3. Creates EquipmentVendor list type items.

        Args:
            model_def: Entity mapping from load-config.yaml.

        Returns:
            Mapping of logical entity names to Kuwaiba class names.
        """
        self._ensure_session()
        class_map: dict[str, str] = {}

        for entity_name, entity_cfg in model_def.items():
            kuwaiba_class = entity_cfg.get("class", entity_name)
            class_map[entity_name] = kuwaiba_class
            log.info("Mapped %s → %s", entity_name, kuwaiba_class)

        # Add containment rules
        # Note: Kuwaiba 2.1 has OLTBoard (subclass of GenericBoard), not CommunicationsBoard
        # Full physical hierarchy: City → Building → Room → Rack → OLT
        # Splitters and ONTs remain under City (field-deployed)
        containment_rules = {
            "City": ["Building", "FiberSplitter", "OpticalNetworkTerminal"],
            "Building": ["Room"],
            "Room": ["Rack"],
            "Rack": ["OpticalLineTerminal"],
            "OpticalLineTerminal": ["Slot"],
            "Slot": ["OLTBoard"],
            "OLTBoard": ["Transceiver", "OpticalPort"],
        }

        for parent_cls, child_classes in containment_rules.items():
            try:
                existing = self._service.getPossibleChildren(parent_cls, self._session_id)
                existing_names = {x["className"] for x in existing} if existing else set()
            except Exception:
                existing_names = set()

            for cls in child_classes:
                if cls in existing_names:
                    log.info("Containment already exists: %s → %s", parent_cls, cls)
                    continue
                try:
                    self._service.addPossibleChildren(parent_cls, [cls], self._session_id)
                    log.info("Added containment rule: %s → %s", parent_cls, cls)
                except Exception as e:
                    if "already" in str(e).lower():
                        log.info("Containment already exists: %s → %s", parent_cls, cls)
                    else:
                        log.warning("Could not add containment %s → %s: %s", parent_cls, cls, e)

        # Create root Country for demo
        try:
            self._country_oid = str(self._service.createObject(
                "Country", "DummyRoot", "-1",
                ["name"], ["GPON Demo"],
                "", self._session_id,
            ))
            log.info("Created root Country 'GPON Demo' oid=%s", self._country_oid)
        except Exception as e:
            log.warning("Could not create Country: %s", e)
            # Try to find existing one
            try:
                objs = self._service.getObjectsOfClassLight("Country", -1, self._session_id)
                if objs:
                    for obj in objs:
                        if obj["name"] == "GPON Demo":
                            self._country_oid = obj["id"]
                            log.info("Found existing Country 'GPON Demo' oid=%s", self._country_oid)
                            break
                    if not self._country_oid and objs:
                        self._country_oid = objs[0]["id"]
                        log.info("Using first Country oid=%s", self._country_oid)
            except Exception as e2:
                log.error("Cannot find or create Country: %s", e2)

        # Create EquipmentVendor list type items
        for vendor_name in ["Huawei", "Nokia", "ZTE"]:
            try:
                self._service.createListTypeItem(
                    "EquipmentVendor", vendor_name, self._session_id
                )
                log.info("Created EquipmentVendor: %s", vendor_name)
            except Exception as e:
                log.debug("EquipmentVendor %s: %s", vendor_name, e)

        self._class_cache = class_map
        return class_map

    # -- object CRUD ---------------------------------------------------------

    def create_object(
        self, entity_type: str, parent_id: str, attributes: dict[str, Any]
    ) -> str:
        """Create a single object in Kuwaiba's containment tree.

        Hierarchy:
            Country("GPON Demo") → City (=site) → Building → Room → Rack → OLT → Slot → OLTBoard → OpticalPort/Transceiver
            City → FiberSplitter (with ports)
            City → OpticalNetworkTerminal (with ports)

        Args:
            entity_type: Logical entity type from the CSV.
            parent_id: OID of the parent object from load_data.py's id_mapping.
            attributes: CSV row as dict.

        Returns:
            The Kuwaiba OID of the newly created object.
        """
        self._ensure_session()

        # Resolve Kuwaiba class name
        class_name = self._class_cache.get(entity_type, entity_type)

        # Determine display name and source ID based on entity type
        _id_fields = {
            "site": ("site_name", "site_id"),
            "rack": ("rack_name", "rack_id"),
            "olt": ("olt_id", "olt_id"),
            "slot": ("slot_id", "slot_id"),
            "line_card": ("card_id", "card_id"),
            "sfp_transceiver": ("sfp_id", "sfp_id"),
            "splitter": ("splitter_id", "splitter_id"),
            "ont": ("ont_id", "ont_id"),
        }
        name_field, id_field = _id_fields.get(entity_type, ("name", "name"))
        obj_name = attributes.get(name_field, "") or attributes.get("name", "") or "unnamed"
        source_id = attributes.get(id_field, "")

        try:
            if entity_type == "site":
                oid = str(self._service.createObject(
                    class_name, "Country", self._country_oid,
                    ["name"], [obj_name],
                    "", self._session_id,
                ))
                with self._lock:
                    self._device_city_map[source_id] = oid
                # Create Building → Room chain under this City for rack placement
                self._ensure_building_room(oid, obj_name)

            elif entity_type == "rack":
                # Racks go under Room (Building → Room created per City)
                city_oid = parent_id  # parent_id is the City OID
                with self._lock:
                    room_oid = self._city_room_map.get(city_oid, "")
                if not room_oid:
                    # Fallback: create room chain now
                    self._ensure_building_room(city_oid, "Site")
                    with self._lock:
                        room_oid = self._city_room_map.get(city_oid, "")
                if not room_oid:
                    raise ValueError(f"No Room OID for rack {source_id}")
                oid = str(self._service.createObject(
                    "Rack", "Room", room_oid,
                    ["name"], [obj_name],
                    "", self._session_id,
                ))
                with self._lock:
                    self._rack_map[source_id] = oid

            elif entity_type == "olt":
                # OLTs go under Rack if rack_id is present, else under City
                city_oid = parent_id  # parent_id is the City OID
                rack_csv_id = attributes.get("rack_id", "")
                if rack_csv_id:
                    with self._lock:
                        rack_oid = self._rack_map.get(rack_csv_id, "")
                    if rack_oid:
                        parent_class = "Rack"
                        parent_oid = rack_oid
                    else:
                        log.warning("Rack %s not found, placing OLT under City", rack_csv_id)
                        parent_class = "City"
                        parent_oid = city_oid
                else:
                    parent_class = "City"
                    parent_oid = city_oid
                attr_names, attr_values = self._build_kuwaiba_attrs(
                    entity_type, obj_name, attributes
                )
                oid = str(self._service.createObject(
                    class_name, parent_class, parent_oid,
                    attr_names, attr_values,
                    "", self._session_id,
                ))
                with self._lock:
                    self._device_city_map[source_id] = city_oid

            elif entity_type == "slot":
                # Slots go inside OLT
                olt_oid = parent_id
                slot_number = attributes.get("slot_number", "")
                oid = str(self._service.createObject(
                    "Slot", "OpticalLineTerminal", olt_oid,
                    ["name"], [f"Slot {slot_number}"],
                    "", self._session_id,
                ))
                with self._lock:
                    self._slot_olt_map[oid] = olt_oid

            elif entity_type == "line_card":
                # OLTBoard goes inside Slot
                slot_oid = parent_id
                attr_names, attr_values = self._build_kuwaiba_attrs(
                    entity_type, obj_name, attributes
                )
                oid = str(self._service.createObject(
                    "OLTBoard", "Slot", slot_oid,
                    attr_names, attr_values,
                    "", self._session_id,
                ))
                with self._lock:
                    self._card_slot_map[oid] = slot_oid
                # Create OpticalPort children on the board
                self._create_ports_on_board(oid, slot_oid, attributes)

            elif entity_type == "sfp_transceiver":
                # Transceiver goes inside OLTBoard
                board_oid = parent_id
                oid = str(self._service.createObject(
                    "Transceiver", "OLTBoard", board_oid,
                    ["name"], [obj_name],
                    "", self._session_id,
                ))

            elif entity_type in ("splitter", "ont"):
                # Splitters and ONTs go under City (flattened)
                with self._lock:
                    city_oid = self._resolve_city_oid(entity_type, parent_id, attributes)
                if not city_oid:
                    raise ValueError(f"No City OID for {entity_type} {source_id}")

                attr_names, attr_values = self._build_kuwaiba_attrs(
                    entity_type, obj_name, attributes
                )
                oid = str(self._service.createObject(
                    class_name, "City", city_oid,
                    attr_names, attr_values,
                    "", self._session_id,
                ))
                with self._lock:
                    self._device_city_map[source_id] = city_oid
                # Create ports for splitters and ONTs
                self._create_ports_for_device(entity_type, oid, class_name, attributes)

            else:
                raise ValueError(f"Unknown entity type: {entity_type}")

            log.info("Created %s '%s' oid=%s", class_name, obj_name, oid)
            return oid

        except Exception as e:
            self._classify_fault(e, class_name, obj_name)
            raise

    def _create_ports_on_board(
        self, board_oid: str, slot_oid: str, attributes: dict,
    ) -> None:
        """Create OpticalPort children on a CommunicationsBoard.

        Port names use 0/{slot}/{port} format. Ports are keyed by OLT OID
        so connection lookup works (connections reference OLT device ID).
        """
        card_type = attributes.get("card_type", "gpon")
        port_count = int(attributes.get("port_count", "16"))
        slot_number = attributes.get("slot_number", "0")

        # Resolve the OLT OID for port map keys
        with self._lock:
            olt_oid = self._slot_olt_map.get(slot_oid, "")

        for port_idx in range(1, port_count + 1):
            if card_type == "gpon":
                port_name = f"0/{slot_number}/{port_idx}"
            else:
                port_name = f"uplink-{port_idx}"

            try:
                port_oid = str(self._service.createObject(
                    "OpticalPort", "OLTBoard", board_oid,
                    ["name"], [port_name],
                    "", self._session_id,
                ))
                # Key by OLT OID so connections can find ports via device_oid:port_name
                with self._lock:
                    if olt_oid:
                        self._port_map[f"{olt_oid}:{port_name}"] = port_oid
                    self._port_map[f"{board_oid}:{port_name}"] = port_oid
            except Exception as e:
                log.debug("Port creation %s on board %s: %s", port_name, board_oid, e)

    def _create_ports_for_device(
        self, entity_type: str, device_oid: str, device_class: str,
        attributes: dict,
    ) -> None:
        """Create OpticalPort objects inside splitters and ONTs.

        Port names match the CSV connection data:
        - FiberSplitter: input port + output-{N} ports
        - ONT: pon port
        """
        ports_to_create: list[str] = []

        if entity_type == "splitter":
            ports_to_create.append("input")
            split_ratio = attributes.get("split_ratio", "1:8")
            try:
                num_outputs = int(split_ratio.split(":")[1])
            except (ValueError, IndexError):
                num_outputs = 8
            for i in range(1, num_outputs + 1):
                ports_to_create.append(f"output-{i}")
        elif entity_type == "ont":
            ports_to_create.append("pon")

        for port_name in ports_to_create:
            try:
                port_oid = str(self._service.createObject(
                    "OpticalPort", device_class, device_oid,
                    ["name"], [port_name],
                    "", self._session_id,
                ))
                with self._lock:
                    self._port_map[f"{device_oid}:{port_name}"] = port_oid
            except Exception as e:
                log.debug("Port creation %s on %s: %s", port_name, device_oid, e)

    def _resolve_city_oid(
        self, entity_type: str, parent_id: str, attributes: dict
    ) -> str:
        """Resolve the City OID for a device.

        For OLTs, parent_id IS the City OID (from id_mapping[parent_site_id]).
        For splitters/ONTs, look up the City via _device_city_map using
        the parent's source ID.
        """
        if entity_type == "olt":
            return parent_id
        else:
            parent_source_id = (
                attributes.get("parent_olt_id", "")
                or attributes.get("parent_splitter_id", "")
            )
            return self._device_city_map.get(parent_source_id, "")

    def _build_kuwaiba_attrs(
        self, entity_type: str, obj_name: str, attributes: dict
    ) -> tuple[list[str], list[str]]:
        """Build parallel attribute name/value arrays for createObject.

        Returns:
            Tuple of (attributeNames, attributeValues).
        """
        names = ["name"]
        values = [str(obj_name)]

        # Build description from CSV fields
        desc_parts = []
        if attributes.get("vendor"):
            desc_parts.append(f"Vendor: {attributes['vendor']}")
        if attributes.get("model"):
            desc_parts.append(f"Model: {attributes['model']}")
        if attributes.get("serial_number"):
            desc_parts.append(f"S/N: {attributes['serial_number']}")
        if attributes.get("status"):
            desc_parts.append(f"Status: {attributes['status']}")
        if desc_parts:
            names.append("description")
            values.append(" | ".join(desc_parts))

        return names, values

    # -- Building/Room chain for rack placement --------------------------------

    def _ensure_building_room(self, city_oid: str, site_name: str) -> None:
        """Create a Building → Room chain under a City for rack placement.

        Idempotent — skips if already created for this City.
        """
        with self._lock:
            if city_oid in self._city_room_map:
                return

        try:
            building_oid = str(self._service.createObject(
                "Building", "City", city_oid,
                ["name"], [f"{site_name} Building"],
                "", self._session_id,
            ))
            room_oid = str(self._service.createObject(
                "Room", "Building", building_oid,
                ["name"], ["Equipment Room"],
                "", self._session_id,
            ))
            with self._lock:
                self._city_room_map[city_oid] = room_oid
            log.info("Created Building/Room chain under City %s", city_oid)
        except Exception as e:
            log.error("Failed to create Building/Room for City %s: %s", city_oid, e)

    # -- connections ---------------------------------------------------------

    def create_connection(
        self,
        a_endpoint_id: str,
        a_port: str,
        b_endpoint_id: str,
        b_port: str,
        connection_type: str,
    ) -> str:
        """Create a physical connection (OpticalLink) between two port objects.

        Kuwaiba's createPhysicalConnection connects OpticalPort objects,
        not devices. The port OIDs are looked up from _port_map using the
        device OID and port name.

        Args:
            a_endpoint_id: OID of the A-side device.
            a_port: Port name on A-side (e.g., "gpon-0/0/3").
            b_endpoint_id: OID of the B-side device.
            b_port: Port name on B-side (e.g., "input").
            connection_type: Fiber type from CSV (ignored; uses OpticalLink).

        Returns:
            OID of the created connection.
        """
        self._ensure_session()
        conn_class = self._config.get("connection_class", "OpticalLink")

        # Resolve port OIDs
        a_port_key = f"{a_endpoint_id}:{a_port}"
        b_port_key = f"{b_endpoint_id}:{b_port}"
        with self._lock:
            a_port_oid = self._port_map.get(a_port_key, "")
            b_port_oid = self._port_map.get(b_port_key, "")

        if not a_port_oid or not b_port_oid:
            log.warning("Port OID not found: a=%s (%s) b=%s (%s)",
                        a_port_key, a_port_oid, b_port_key, b_port_oid)
            raise ValueError(f"Port OID not found for {a_port_key} or {b_port_key}")

        conn_name = f"{a_port}--{b_port}"

        try:
            result = self._service.createPhysicalConnection(
                "OpticalPort",     # aObjectClass
                a_port_oid,        # aObjectId
                "OpticalPort",     # bObjectClass
                b_port_oid,        # bObjectId
                conn_name,         # name
                conn_class,        # connectionClass
                "",                # templateId
                self._session_id,
            )
            oid = str(result)
            log.info("Created %s '%s' oid=%s", conn_class, conn_name, oid)
            return oid
        except Exception as e:
            log.error("Failed to create connection %s: %s", conn_name, e)
            raise

    # -- visualization -------------------------------------------------------

    def create_visualization(
        self,
        id_mapping: dict[str, str],
        site_rows: list[dict],
        connection_rows: list[dict],
        device_rows: dict[str, list[dict]] | None = None,
    ) -> None:
        """Create an Outside Plant (OSP) View in Kuwaiba.

        Places all devices on an OpenStreetMap view using GPS coordinates.
        If device CSVs contain per-device lat/lng columns, those are used
        directly for realistic placement. Otherwise falls back to uniform
        ring offsets around the parent site center.

        Args:
            id_mapping: source_id → Kuwaiba OID for all created objects.
            site_rows: Parsed rows from sites.csv (need latitude, longitude).
            connection_rows: Parsed rows from connections.csv.
            device_rows: Optional dict of entity_type → CSV rows with lat/lng.
        """
        self._ensure_session()

        # Build site coordinate lookup: site_id → (lat, lon)
        site_coords: dict[str, tuple[float, float]] = {}
        for row in site_rows:
            sid = row.get("site_id", "")
            try:
                lat = float(row.get("latitude", 0))
                lon = float(row.get("longitude", 0))
                site_coords[sid] = (lat, lon)
            except (ValueError, TypeError):
                pass

        if not site_coords:
            log.warning("No site coordinates available; skipping OSP view")
            return

        # Compute map center
        all_lats = [c[0] for c in site_coords.values()]
        all_lons = [c[1] for c in site_coords.values()]
        center_lat = sum(all_lats) / len(all_lats)
        center_lon = sum(all_lons) / len(all_lons)

        # Build per-device coordinate lookup from device_rows if available
        device_coords: dict[str, tuple[float, float]] = {}  # source_id → (lat, lng)
        if device_rows:
            for entity_type, rows in device_rows.items():
                id_field = {
                    "olt": "olt_id", "splitter": "splitter_id", "ont": "ont_id",
                }.get(entity_type, "")
                for row in rows:
                    src_id = row.get(id_field, "")
                    if src_id and row.get("latitude") and row.get("longitude"):
                        try:
                            device_coords[src_id] = (
                                float(row["latitude"]), float(row["longitude"]),
                            )
                        except (ValueError, TypeError):
                            pass

        has_device_coords = bool(device_coords)

        # Assign GPS coords to each device
        # node_positions: kuwaiba_oid → (lat, lon, kuwaiba_class)
        node_positions: dict[str, tuple[float, float, str]] = {}

        # --- OLTs ---
        if has_device_coords:
            for source_id, oid in id_mapping.items():
                if not source_id.startswith("OLT-"):
                    continue
                coords = device_coords.get(source_id)
                if coords:
                    node_positions[oid] = (coords[0], coords[1], "OpticalLineTerminal")
        else:
            # Fallback: ring around site center
            olt_per_site: dict[str, list[str]] = {}
            for source_id, oid in id_mapping.items():
                if source_id.startswith("OLT-"):
                    parts = source_id.split("-")
                    site_id = f"{parts[1]}-{parts[2]}"
                    olt_per_site.setdefault(site_id, []).append(source_id)
            for site_id, olt_ids in olt_per_site.items():
                base = site_coords.get(site_id, (center_lat, center_lon))
                for i, olt_id in enumerate(sorted(olt_ids)):
                    oid = id_mapping.get(olt_id, "")
                    if not oid:
                        continue
                    angle = 2 * math.pi * i / max(len(olt_ids), 1)
                    lat = base[0] + 0.001 * math.cos(angle)
                    lon = base[1] + 0.001 * math.sin(angle)
                    node_positions[oid] = (lat, lon, "OpticalLineTerminal")

        # --- Splitters ---
        if has_device_coords:
            for source_id, oid in id_mapping.items():
                if not source_id.startswith("SPL"):
                    continue
                coords = device_coords.get(source_id)
                if coords:
                    node_positions[oid] = (coords[0], coords[1], "FiberSplitter")
        else:
            spl_per_site: dict[str, list[str]] = {}
            for source_id, oid in id_mapping.items():
                if source_id.startswith("SPL-"):
                    parts = source_id.split("-")
                    site_id = f"{parts[2]}-{parts[3]}"
                    spl_per_site.setdefault(site_id, []).append(source_id)
            for site_id, spl_ids in spl_per_site.items():
                base = site_coords.get(site_id, (center_lat, center_lon))
                for i, spl_id in enumerate(sorted(spl_ids)):
                    oid = id_mapping.get(spl_id, "")
                    if not oid:
                        continue
                    angle = 2 * math.pi * i / max(len(spl_ids), 1)
                    lat = base[0] + 0.003 * math.cos(angle)
                    lon = base[1] + 0.003 * math.sin(angle)
                    node_positions[oid] = (lat, lon, "FiberSplitter")

        # --- ONTs ---
        if has_device_coords:
            for source_id, oid in id_mapping.items():
                if not source_id.startswith("ONT-"):
                    continue
                coords = device_coords.get(source_id)
                if coords:
                    node_positions[oid] = (coords[0], coords[1], "OpticalNetworkTerminal")
        else:
            ont_per_site: dict[str, list[str]] = {}
            for source_id, oid in id_mapping.items():
                if source_id.startswith("ONT-"):
                    parent_spl = None
                    for row in connection_rows:
                        if (row.get("b_endpoint_id") == source_id
                                and row.get("a_endpoint_type") == "splitter"):
                            parent_spl = row.get("a_endpoint_id", "")
                            break
                    if parent_spl:
                        parts = parent_spl.split("-")
                        site_id = f"{parts[2]}-{parts[3]}"
                    else:
                        continue
                    ont_per_site.setdefault(site_id, []).append(source_id)
            for site_id, ont_ids in ont_per_site.items():
                base = site_coords.get(site_id, (center_lat, center_lon))
                for i, ont_id in enumerate(sorted(ont_ids)):
                    oid = id_mapping.get(ont_id, "")
                    if not oid:
                        continue
                    angle = 2 * math.pi * i / max(len(ont_ids), 1)
                    lat = base[0] + 0.006 * math.cos(angle)
                    lon = base[1] + 0.006 * math.sin(angle)
                    node_positions[oid] = (lat, lon, "OpticalNetworkTerminal")

        # Build edges from connection rows.
        # OSP edges connect *nodes* (devices), not ports. The asideid/bsideid
        # must match OIDs in the <nodes> section, with two control points
        # (one at each endpoint) so the line renders on the map.
        edges_xml_parts: list[str] = []
        seen_edges: set[tuple[str, str]] = set()
        for row in connection_rows:
            a_source = row.get("a_endpoint_id", "")
            b_source = row.get("b_endpoint_id", "")
            a_device_oid = id_mapping.get(a_source, "")
            b_device_oid = id_mapping.get(b_source, "")
            if not a_device_oid or not b_device_oid:
                continue

            # Deduplicate edges between the same pair of devices
            edge_key = (min(a_device_oid, b_device_oid), max(a_device_oid, b_device_oid))
            if edge_key in seen_edges:
                continue
            seen_edges.add(edge_key)

            a_pos = node_positions.get(a_device_oid)
            b_pos = node_positions.get(b_device_oid)
            if not a_pos or not b_pos:
                continue

            # Connection OID from the physical connection we created earlier.
            # Falls back to a random UUID if the real OID wasn't captured.
            conn_id = row.get("connection_id", "")
            conn_oid = id_mapping.get(conn_id, "")
            if not conn_oid:
                conn_oid = str(uuid.uuid4())

            edges_xml_parts.append(
                f'<edge id="{conn_oid}" class="OpticalLink" '
                f'asideid="{a_device_oid}" asideclass="{a_pos[2]}" '
                f'bsideid="{b_device_oid}" bsideclass="{b_pos[2]}">'
                f'<controlpoint lat="{a_pos[0]}" lon="{a_pos[1]}"/>'
                f'<controlpoint lat="{b_pos[0]}" lon="{b_pos[1]}"/>'
                f'</edge>'
            )

        # Build nodes XML (self-closing tags with lat/lon attributes)
        nodes_xml_parts: list[str] = []
        for oid, (lat, lon, cls) in node_positions.items():
            nodes_xml_parts.append(
                f'<node lat="{lat}" lon="{lon}" class="{cls}">{oid}</node>'
            )

        # Assemble full OSP View XML matching Kuwaiba 2.1's expected format.
        # Use version="1.0" and include metadata attributes present in
        # built-in views (syncGeoPosition, unitOfLength, computeEdgesLength).
        osp_xml = (
            '<view version="1.0">'
            '<class>OSPView</class>'
            f'<center lat="{center_lat}" lon="{center_lon}"/>'
            '<mapTypeId>roadmap</mapTypeId>'
            '<syncGeoPosition>true</syncGeoPosition>'
            '<unitOfLength>m</unitOfLength>'
            '<computeEdgesLength>true</computeEdgesLength>'
            '<zoom>8.0</zoom>'
            '<nodes>'
            + "".join(nodes_xml_parts)
            + '</nodes>'
            '<edges>'
            + "".join(edges_xml_parts)
            + '</edges>'
            '</view>'
        )

        # Call createOSPView via SOAP
        try:
            view_id = self._service.createOSPView(
                "GPON Demo Network",          # name
                "GPON network topology with OLTs, splitters, and ONTs "
                "placed on OpenStreetMap.",    # description
                osp_xml.encode("utf-8"),       # content as byte[]
                self._session_id,
            )
            log.info(
                "Created OSP View 'GPON Demo Network' (id=%s) with %d nodes, %d edges",
                view_id, len(nodes_xml_parts), len(edges_xml_parts),
            )
        except Exception as e:
            log.error("Failed to create OSP View: %s", e)

    # -- verification --------------------------------------------------------

    def verify_load(self, class_name: str, expected_count: int) -> bool:
        """Query object count for a given class and compare."""
        self._ensure_session()
        try:
            result = self._service.getObjectsOfClassLight(
                class_name, -1, self._session_id
            )
            actual = len(result) if result else 0
            ok = actual >= expected_count
            log.info("verify %s: expected=%d actual=%d pass=%s",
                     class_name, expected_count, actual, ok)
            return ok
        except Exception as e:
            log.error("Verification failed for %s: %s", class_name, e)
            return False

    # -- service inventory (CFS/RFS) -----------------------------------------

    def setup_service_model(self, service_config: dict) -> None:
        """Create custom CFS/RFS subclasses of GenericService and their attributes.

        Uses Kuwaiba's createClass and createAttribute SOAP methods.
        Idempotent — skips if classes/attributes already exist.
        """
        self._ensure_session()

        class_defs = [
            {
                "name": service_config.get("cfs_class", "GPONBroadbandCFS"),
                "parent": "GenericService",
                "attributes": [
                    ("serviceTier", "String"),
                    ("bandwidthDown", "Integer"),
                    ("bandwidthUp", "Integer"),
                ],
            },
            {
                "name": service_config.get("rfs_class", "GPONAccessRFS"),
                "parent": "GenericService",
                "attributes": [
                    ("vlanId", "Integer"),
                    ("ponPath", "String"),
                ],
            },
        ]

        for cdef in class_defs:
            try:
                self._service.createClass(
                    cdef["name"],       # className
                    "",                 # displayName
                    "",                 # description
                    False,              # isAbstract
                    True,               # isCustom
                    False,              # isCountable
                    False,              # isInDesign
                    cdef["parent"],     # parentClassName
                    None,               # icon
                    None,               # smallIcon
                    0,                  # color
                    self._session_id,
                )
                log.info("Created service class: %s", cdef["name"])
            except Exception as e:
                if "already" in str(e).lower() or "exist" in str(e).lower():
                    log.info("Service class already exists: %s", cdef["name"])
                else:
                    log.warning("Could not create class %s: %s", cdef["name"], e)

            for attr_name, attr_type in cdef["attributes"]:
                try:
                    self._service.createAttribute(
                        cdef["name"],   # className
                        attr_name,      # name
                        attr_name,      # displayName
                        attr_type,      # type
                        "",             # description
                        False,          # administrative
                        True,           # visible
                        False,          # isReadOnly
                        False,          # noCopy
                        False,          # unique
                        False,          # mandatory
                        False,          # multiple
                        0,              # order
                        self._session_id,
                    )
                    log.info("Created attribute %s.%s", cdef["name"], attr_name)
                except Exception as e:
                    if "already" in str(e).lower() or "exist" in str(e).lower():
                        log.debug("Attribute %s.%s already exists", cdef["name"], attr_name)
                    else:
                        log.warning("Could not create attribute %s.%s: %s",
                                    cdef["name"], attr_name, e)

        self._service_config = service_config

    def create_customer_pool(self, pool_name: str) -> str:
        """Create a customer pool under the root. Returns pool OID."""
        self._ensure_session()
        if hasattr(self, "_customer_pool_oid") and self._customer_pool_oid:
            return self._customer_pool_oid

        try:
            oid = str(self._service.createCustomerPool(
                pool_name,          # poolName
                "",                 # poolDescription
                self._session_id,
            ))
            log.info("Created customer pool '%s' oid=%s", pool_name, oid)
            self._customer_pool_oid = oid
            return oid
        except Exception as e:
            log.error("Failed to create customer pool: %s", e)
            raise

    def create_customer(self, pool_oid: str, customer_name: str,
                        attributes: dict) -> str:
        """Create a customer inside a pool. Returns customer OID."""
        self._ensure_session()
        try:
            oid = str(self._service.createCustomer(
                pool_oid,           # poolId
                "HomeCustomer",     # customerClass (concrete subclass)
                ["name"],           # attributeNames
                [customer_name],    # attributeValues
                self._session_id,
            ))
            log.info("Created customer '%s' oid=%s", customer_name, oid)
            return oid
        except Exception as e:
            log.error("Failed to create customer '%s': %s", customer_name, e)
            raise

    def create_service_pool(self, customer_oid: str, pool_name: str) -> str:
        """Create a service pool under a customer. Returns pool OID."""
        self._ensure_session()
        try:
            oid = str(self._service.createServicePool(
                "HomeCustomer",     # customerClass (concrete)
                customer_oid,       # customerId
                pool_name,          # poolName
                "",                 # poolDescription
                self._session_id,
            ))
            log.info("Created service pool '%s' under customer %s", pool_name, customer_oid)
            return oid
        except Exception as e:
            log.error("Failed to create service pool: %s", e)
            raise

    def create_service(self, pool_oid: str, service_class: str,
                       service_name: str, attr_names: list[str],
                       attr_values: list[str]) -> str:
        """Create a CFS or RFS service instance in a service pool."""
        self._ensure_session()
        try:
            oid = str(self._service.createService(
                pool_oid,           # poolId
                service_class,      # serviceClass
                attr_names,         # attributeNames
                attr_values,        # attributeValues
                self._session_id,
            ))
            log.info("Created %s '%s' oid=%s", service_class, service_name, oid)
            return oid
        except Exception as e:
            log.error("Failed to create service %s '%s': %s",
                      service_class, service_name, e)
            raise

    def relate_service_to_resource(self, resource_class: str, resource_oid: str,
                                   service_class: str, service_oid: str) -> None:
        """Link a service (RFS) to a physical resource via relateObjectToService."""
        self._ensure_session()
        try:
            self._service.relateObjectToService(
                resource_class,     # objectClass
                resource_oid,       # objectId
                service_class,      # serviceClass
                service_oid,        # serviceId
                self._session_id,
            )
            log.debug("Linked %s %s → service %s", resource_class, resource_oid, service_oid)
        except Exception as e:
            log.warning("Failed to link resource %s to service %s: %s",
                        resource_oid, service_oid, e)

    def relate_cfs_to_rfs(self, cfs_oid: str, rfs_oid: str) -> None:
        """Link a CFS to its underlying RFS."""
        self._ensure_session()
        cfs_class = getattr(self, "_service_config", {}).get(
            "cfs_class", "GPONBroadbandCFS")
        rfs_class = getattr(self, "_service_config", {}).get(
            "rfs_class", "GPONAccessRFS")
        try:
            self._service.relateObjectToService(
                cfs_class, cfs_oid, rfs_class, rfs_oid, self._session_id,
            )
            log.debug("Linked CFS %s → RFS %s", cfs_oid, rfs_oid)
        except Exception as e:
            log.warning("Failed to link CFS %s to RFS %s: %s", cfs_oid, rfs_oid, e)

    def verify_service_impact(self, service_pool_oid: str) -> list:
        """Verify services were created by listing services in a pool."""
        self._ensure_session()
        try:
            result = self._service.getServicesInPool(
                service_pool_oid,   # poolId
                "GenericService",   # className
                0,                  # page
                100,                # limit
                self._session_id,
            )
            services = list(result) if result else []
            log.info("getServicesInPool(%s) → %d services", service_pool_oid, len(services))
            return services
        except Exception as e:
            log.warning("getServicesInPool failed for pool %s: %s",
                        service_pool_oid, e)
            return []

    # -- error handling ------------------------------------------------------

    @staticmethod
    def _classify_fault(error: Exception, class_name: str, obj_name: str) -> None:
        """Log SOAP fault details with context."""
        error_str = str(error).lower()
        if "containment" in error_str:
            log.error(
                "Containment error creating %s '%s': The parent class may not "
                "allow children of type %s. Check Kuwaiba containment rules.",
                class_name, obj_name, class_name,
            )
        elif "already exists" in error_str or "duplicate" in error_str:
            log.warning("Duplicate %s '%s' — may already exist.", class_name, obj_name)
        elif "session" in error_str:
            log.error("Session error — may need to reconnect.")
        else:
            log.error("SOAP fault creating %s '%s': %s", class_name, obj_name, error)
