#!/usr/bin/env python3
# =============================================================================
# load_data.py
# Generated by: target-loader-adapter | Date: 2026-02-19
# Purpose: CLI to read generated CSVs and load into Kuwaiba or NetBox.
# Assumptions: Python 3.10+, adapter dependencies (zeep or requests).
# =============================================================================

"""Load GPON synthetic data from CSVs into a target inventory system.

Usage::

    python load_data.py --adapter netbox --config load-config.yaml --data-dir ../synthetic/output
    python load_data.py --adapter kuwaiba --config load-config.yaml --data-dir ../synthetic/output
    python load_data.py --adapter netbox --config load-config.yaml --data-dir ../synthetic/output --dry-run

Reads CSVs produced by generate_synthetic_data.py and loads them into
the selected target system using the appropriate adapter.
"""

import argparse
import csv
import logging
import sys
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any

log = logging.getLogger(__name__)

# Try to load PyYAML; fall back to a minimal parser.
try:
    import yaml  # type: ignore[import-untyped]
except ImportError:
    yaml = None  # type: ignore[assignment]


def _minimal_load_config(path: Path) -> dict:
    """Parse load-config.yaml without PyYAML.

    Handles the flat key-value structure with nested mappings used by
    load-config.yaml.  Not a general YAML parser.
    """
    import re

    text = path.read_text()
    result: dict = {}
    stack: list[tuple[int, dict]] = [(-1, result)]  # (indent, dict)

    # Track list-mode: when a key has no value and the next lines are "- item"
    pending_list_key: str | None = None
    pending_list_indent: int = -1
    pending_list: list = []
    pending_list_parent: dict | None = None

    def _flush_list():
        nonlocal pending_list_key, pending_list, pending_list_parent
        if pending_list_key and pending_list_parent is not None and pending_list:
            pending_list_parent[pending_list_key] = pending_list
        pending_list_key = None
        pending_list = []
        pending_list_parent = None

    for raw_line in text.splitlines():
        # Strip inline comments (outside quotes)
        line = re.sub(r'\s+#.*$', '', raw_line)
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue

        indent = len(line) - len(line.lstrip())

        # Check for YAML list item: "- value"
        if stripped.startswith("- "):
            if pending_list_key:
                item = stripped[2:].strip().strip('"').strip("'")
                pending_list.append(item)
                continue

        # If we were collecting a list and hit a non-list line, flush
        if pending_list_key and not stripped.startswith("- "):
            _flush_list()

        # Pop stack to find parent at correct indentation
        while len(stack) > 1 and stack[-1][0] >= indent:
            stack.pop()

        parent = stack[-1][1]

        if ":" not in stripped:
            continue

        key, _, val = stripped.partition(":")
        key = key.strip()
        val = val.strip().strip('"').strip("'")

        if not val:
            # Could be a nested dict or a list (determined by next lines)
            new_dict: dict = {}
            parent[key] = new_dict
            stack.append((indent, new_dict))
            # Also set up potential list collection
            pending_list_key = key
            pending_list_indent = indent
            pending_list = []
            pending_list_parent = parent
        elif val.startswith("[") and val.endswith("]"):
            # Inline list
            items = [v.strip().strip('"').strip("'") for v in val[1:-1].split(",")]
            parent[key] = items
        elif val == "null":
            parent[key] = None
        else:
            # Try numeric
            try:
                parent[key] = int(val)
            except ValueError:
                try:
                    parent[key] = float(val)
                except ValueError:
                    parent[key] = val

    _flush_list()
    return result


def load_yaml(path: Path) -> dict:
    """Load a YAML file."""
    if yaml is not None:
        with open(path) as f:
            return yaml.safe_load(f)
    log.info("PyYAML not installed; using minimal built-in parser")
    return _minimal_load_config(path)


def read_csv(filepath: Path) -> list[dict]:
    """Read a CSV file into a list of dicts."""
    with open(filepath, newline="") as f:
        reader = csv.DictReader(f)
        return list(reader)


def get_adapter(adapter_name: str):
    """Import and instantiate the requested adapter."""
    if adapter_name == "netbox":
        from netbox_adapter import NetBoxAdapter
        return NetBoxAdapter()
    elif adapter_name == "kuwaiba":
        from kuwaiba_adapter import KuwaibaAdapter
        return KuwaibaAdapter()
    else:
        raise ValueError(f"Unknown adapter: {adapter_name}. Use 'netbox' or 'kuwaiba'.")


def _load_one_entity(
    adapter,
    entity_type: str,
    row: dict,
    id_mapping: dict[str, str],
    id_mapping_lock: threading.Lock,
    parent_field: str | None,
    id_field: str,
) -> bool:
    """Load a single entity. Returns True on success, False on error."""
    source_id = row.get(id_field, "")

    # Resolve parent
    parent_target_id = ""
    if parent_field and parent_field in row:
        parent_source_id = row[parent_field]
        with id_mapping_lock:
            parent_target_id = id_mapping.get(parent_source_id, "")
        if not parent_target_id:
            log.warning(
                "Parent %s not found in mapping for %s %s",
                parent_source_id, entity_type, source_id,
            )

    try:
        target_id = adapter.create_object(entity_type, parent_target_id, dict(row))
        with id_mapping_lock:
            id_mapping[source_id] = target_id
        return True
    except Exception as e:
        log.error("Failed to create %s %s: %s", entity_type, source_id, e)
        raise


def load_entities(
    adapter,
    entity_type: str,
    rows: list[dict],
    id_mapping: dict[str, str],
    parent_field: str | None,
    dry_run: bool,
    fail_fast: bool,
    max_workers: int = 1,
) -> tuple[int, int]:
    """Load a batch of entities into the target system.

    Args:
        adapter: The target adapter instance.
        entity_type: Entity type (site, olt, splitter, ont).
        rows: CSV rows as dicts.
        id_mapping: Mapping of source_id → target_id (updated in place).
        parent_field: CSV column name for parent reference, or None.
        dry_run: If True, log but don't create.
        fail_fast: If True, stop on first error.
        max_workers: Number of parallel threads (1 = sequential).

    Returns:
        Tuple of (success_count, error_count).
    """
    success = 0
    errors = 0

    # Map entity_type to the CSV column that holds its primary ID
    id_field_map = {
        "site": "site_id",
        "rack": "rack_id",
        "olt": "olt_id",
        "slot": "slot_id",
        "line_card": "card_id",
        "splitter": "splitter_id",
        "sfp_transceiver": "sfp_id",
        "ont": "ont_id",
    }
    id_field = id_field_map.get(entity_type, f"{entity_type}_id")

    if dry_run:
        for row in rows:
            source_id = row.get(id_field, "")
            parent_target_id = ""
            if parent_field and parent_field in row:
                parent_target_id = id_mapping.get(row[parent_field], "")
            log.info("[DRY RUN] Would create %s: %s (parent=%s)",
                     entity_type, source_id, parent_target_id or "root")
            id_mapping[source_id] = f"dry-run-{source_id}"
            success += 1
        return success, errors

    # Bulk path: use adapter's array POST when supported (not for slots)
    if (
        hasattr(adapter, "create_objects_bulk")
        and hasattr(adapter, "BULK_ENTITY_TYPES")
        and entity_type in adapter.BULK_ENTITY_TYPES
    ):
        items = []
        for row in rows:
            source_id = row.get(id_field, "")
            parent_target_id = ""
            if parent_field and parent_field in row:
                parent_source_id = row[parent_field]
                parent_target_id = id_mapping.get(parent_source_id, "")
                if not parent_target_id:
                    log.warning("Parent %s not found for %s %s",
                                parent_source_id, entity_type, source_id)
            items.append((source_id, parent_target_id, dict(row)))
        try:
            result_map = adapter.create_objects_bulk(entity_type, items)
            id_mapping.update(result_map)
            return len(result_map), len(items) - len(result_map)
        except Exception as e:
            log.error("Bulk create failed for %s: %s", entity_type, e)
            if fail_fast:
                raise
            return 0, len(items)

    # Per-item path (slots and adapters without bulk support)
    id_mapping_lock = threading.Lock()

    if max_workers <= 1:
        # Sequential path — no thread overhead
        for row in rows:
            try:
                _load_one_entity(
                    adapter, entity_type, row, id_mapping,
                    id_mapping_lock, parent_field, id_field,
                )
                success += 1
            except Exception:
                errors += 1
                if fail_fast:
                    raise
    else:
        with ThreadPoolExecutor(max_workers=max_workers) as pool:
            futures = {
                pool.submit(
                    _load_one_entity,
                    adapter, entity_type, row, id_mapping,
                    id_mapping_lock, parent_field, id_field,
                ): row
                for row in rows
            }
            for future in as_completed(futures):
                try:
                    future.result()
                    success += 1
                except Exception:
                    errors += 1
                    if fail_fast:
                        # Cancel remaining futures
                        for f in futures:
                            f.cancel()
                        raise

    return success, errors


def _load_one_connection(
    adapter,
    row: dict,
    id_mapping: dict[str, str],
    id_mapping_lock: threading.Lock,
) -> bool:
    """Load a single connection. Returns True on success, False on error."""
    with id_mapping_lock:
        a_id = id_mapping.get(row["a_endpoint_id"], "")
        b_id = id_mapping.get(row["b_endpoint_id"], "")

    a_port = row.get("a_port", "")
    b_port = row.get("b_port", "")
    fiber_type = row.get("fiber_type", "smf")

    if not a_id or not b_id:
        log.warning(
            "Skipping connection %s: endpoint not in mapping (a=%s b=%s)",
            row.get("connection_id", "?"), row["a_endpoint_id"], row["b_endpoint_id"],
        )
        raise ValueError(f"Endpoint not in mapping for {row.get('connection_id', '?')}")

    conn_oid = adapter.create_connection(a_id, a_port, b_id, b_port, fiber_type)
    conn_key = row.get("connection_id", "")
    if conn_oid and conn_key:
        with id_mapping_lock:
            id_mapping[conn_key] = conn_oid
    return True


def load_connections(
    adapter,
    rows: list[dict],
    id_mapping: dict[str, str],
    dry_run: bool,
    fail_fast: bool,
    max_workers: int = 1,
) -> tuple[int, int]:
    """Load connection (cable/fiber) records.

    Returns:
        Tuple of (success_count, error_count).
    """
    success = 0
    errors = 0

    if dry_run:
        for row in rows:
            a_id = id_mapping.get(row["a_endpoint_id"], "")
            b_id = id_mapping.get(row["b_endpoint_id"], "")
            a_port = row.get("a_port", "")
            b_port = row.get("b_port", "")
            log.info("[DRY RUN] Would create connection: %s:%s ↔ %s:%s",
                     a_id, a_port, b_id, b_port)
            success += 1
        return success, errors

    # Per-item threaded path — faster than bulk for cables because Django's
    # multiple gunicorn workers parallelize individual requests better than
    # a single bulk transaction.
    id_mapping_lock = threading.Lock()

    if max_workers <= 1:
        for row in rows:
            try:
                _load_one_connection(adapter, row, id_mapping, id_mapping_lock)
                success += 1
            except Exception as e:
                errors += 1
                if fail_fast:
                    raise
    else:
        with ThreadPoolExecutor(max_workers=max_workers) as pool:
            futures = {
                pool.submit(
                    _load_one_connection, adapter, row, id_mapping, id_mapping_lock,
                ): row
                for row in rows
            }
            for future in as_completed(futures):
                try:
                    future.result()
                    success += 1
                except Exception:
                    errors += 1
                    if fail_fast:
                        for f in futures:
                            f.cancel()
                        raise

    return success, errors


def load_services(
    adapter,
    data_dir: Path,
    id_mapping: dict[str, str],
    service_config: dict,
    dry_run: bool,
) -> dict[str, tuple[int, int]]:
    """Load CFS/RFS service inventory into Kuwaiba.

    Reads subscribers.csv, services_cfs.csv, services_rfs.csv,
    service_resource_links.csv and orchestrates customer/pool/service
    creation and resource linking.

    Returns:
        Dict of entity → (success, errors) counts.
    """
    results: dict[str, tuple[int, int]] = {}

    # Check if service CSVs exist
    sub_csv = data_dir / "subscribers.csv"
    cfs_csv = data_dir / "services_cfs.csv"
    rfs_csv = data_dir / "services_rfs.csv"
    srl_csv = data_dir / "service_resource_links.csv"

    if not sub_csv.exists():
        log.info("No subscribers.csv found — skipping service loading")
        return results

    subscribers = read_csv(sub_csv)
    cfs_rows = read_csv(cfs_csv) if cfs_csv.exists() else []
    rfs_rows = read_csv(rfs_csv) if rfs_csv.exists() else []
    srl_rows = read_csv(srl_csv) if srl_csv.exists() else []

    cfs_class = service_config.get("cfs_class", "GPONBroadbandCFS")
    rfs_class = service_config.get("rfs_class", "GPONAccessRFS")
    pool_name = service_config.get("customer_pool_name", "GPON Demo Customers")

    if dry_run:
        results["subscriber"] = (len(subscribers), 0)
        results["cfs"] = (len(cfs_rows), 0)
        results["rfs"] = (len(rfs_rows), 0)
        results["service_link"] = (len(srl_rows), 0)
        log.info("[DRY RUN] Would load %d subscribers, %d CFS, %d RFS, %d links",
                 len(subscribers), len(cfs_rows), len(rfs_rows), len(srl_rows))
        return results

    # Setup service model (create classes + attributes)
    adapter.setup_service_model(service_config)

    # Create customer pool
    pool_oid = adapter.create_customer_pool(pool_name)

    # Create customers (one per subscriber)
    sub_ok, sub_err = 0, 0
    customer_map: dict[str, str] = {}   # subscriber_id → customer_oid
    svc_pool_map: dict[str, str] = {}   # subscriber_id → service_pool_oid
    for sub in subscribers:
        try:
            cust_oid = adapter.create_customer(
                pool_oid, sub["customer_name"], sub,
            )
            customer_map[sub["subscriber_id"]] = cust_oid
            # Create a service pool per customer
            sp_oid = adapter.create_service_pool(cust_oid, "Services")
            svc_pool_map[sub["subscriber_id"]] = sp_oid
            sub_ok += 1
        except Exception as e:
            log.error("Failed to create subscriber %s: %s", sub["subscriber_id"], e)
            sub_err += 1
    results["subscriber"] = (sub_ok, sub_err)

    # Create CFS instances
    cfs_ok, cfs_err = 0, 0
    cfs_map: dict[str, str] = {}  # cfs_id → service_oid
    for cfs in cfs_rows:
        sp_oid = svc_pool_map.get(cfs["subscriber_id"], "")
        if not sp_oid:
            cfs_err += 1
            continue
        try:
            svc_oid = adapter.create_service(
                sp_oid, cfs_class, cfs["service_tier"],
                ["name", "serviceTier", "bandwidthDown", "bandwidthUp"],
                [cfs["service_tier"], cfs["service_tier"],
                 str(cfs["bandwidth_down_mbps"]), str(cfs["bandwidth_up_mbps"])],
            )
            cfs_map[cfs["cfs_id"]] = svc_oid
            cfs_ok += 1
        except Exception:
            cfs_err += 1
    results["cfs"] = (cfs_ok, cfs_err)

    # Create RFS instances
    rfs_ok, rfs_err = 0, 0
    rfs_map: dict[str, str] = {}  # rfs_id → service_oid
    for rfs in rfs_rows:
        cfs_oid = cfs_map.get(rfs["cfs_id"], "")
        # Find the subscriber for this CFS to locate the service pool
        cfs_row = next((c for c in cfs_rows if c["cfs_id"] == rfs["cfs_id"]), None)
        if not cfs_row:
            rfs_err += 1
            continue
        sp_oid = svc_pool_map.get(cfs_row["subscriber_id"], "")
        if not sp_oid:
            rfs_err += 1
            continue
        try:
            svc_oid = adapter.create_service(
                sp_oid, rfs_class, f"PON Path {rfs['ont_id']}",
                ["name", "vlanId", "ponPath"],
                [f"PON Path {rfs['ont_id']}", str(rfs["vlan_id"]), rfs["pon_path"]],
            )
            rfs_map[rfs["rfs_id"]] = svc_oid
            rfs_ok += 1
            # Link CFS → RFS
            if cfs_oid:
                adapter.relate_cfs_to_rfs(cfs_oid, svc_oid)
        except Exception:
            rfs_err += 1
    results["rfs"] = (rfs_ok, rfs_err)

    # Resource class mapping for relateObjectToService
    resource_class_map = {
        "ont": "OpticalNetworkTerminal",
        "olt": "OpticalLineTerminal",
        "splitter": "FiberSplitter",
        "connection": "OpticalLink",
    }

    # Create resource links (RFS → physical resources)
    link_ok, link_err = 0, 0
    for srl in srl_rows:
        rfs_oid = rfs_map.get(srl["rfs_id"], "")
        resource_oid = id_mapping.get(srl["resource_id"], "")
        resource_class = resource_class_map.get(srl["resource_type"], "")
        if not rfs_oid or not resource_oid or not resource_class:
            link_err += 1
            continue
        try:
            adapter.relate_service_to_resource(resource_class, resource_oid, rfs_class, rfs_oid)
            link_ok += 1
        except Exception:
            link_err += 1
    results["service_link"] = (link_ok, link_err)

    # Verify: pick a sample service pool and list its services
    sample_pool_oid = ""
    for sp_oid in svc_pool_map.values():
        if sp_oid:
            sample_pool_oid = sp_oid
            break
    if sample_pool_oid:
        services = adapter.verify_service_impact(sample_pool_oid)
        log.info("Service verification: pool %s has %d services",
                 sample_pool_oid, len(services))

    return results


def print_summary(results: dict[str, tuple[int, int]], elapsed: float) -> None:
    """Print a summary table of load results."""
    print("\n" + "=" * 60)
    print(f"{'Entity':<15} {'Success':>10} {'Errors':>10}")
    print("-" * 60)
    total_ok = 0
    total_err = 0
    for entity, (ok, err) in results.items():
        print(f"{entity:<15} {ok:>10} {err:>10}")
        total_ok += ok
        total_err += err
    print("-" * 60)
    print(f"{'TOTAL':<15} {total_ok:>10} {total_err:>10}")
    print(f"\nElapsed: {elapsed:.1f}s")
    print("=" * 60)


# -- Parent field mapping ---------------------------------------------------

PARENT_FIELDS: dict[str, str | None] = {
    "site": None,
    "rack": "parent_site_id",
    "olt": "parent_site_id",
    "slot": "parent_olt_id",
    "line_card": "parent_slot_id",
    "splitter": "parent_olt_id",
    "sfp_transceiver": "parent_card_id",
    "ont": "parent_splitter_id",
}


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Load GPON synthetic data into a target inventory system."
    )
    parser.add_argument(
        "--adapter", required=True, choices=["netbox", "kuwaiba"],
        help="Target adapter to use.",
    )
    parser.add_argument(
        "--config", default="load-config.yaml",
        help="Path to load configuration YAML (default: load-config.yaml).",
    )
    parser.add_argument(
        "--data-dir", default="../synthetic/output",
        help="Directory containing generated CSVs (default: ../synthetic/output).",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Log operations without creating objects.",
    )
    parser.add_argument(
        "--fail-fast", action="store_true",
        help="Stop on first error.",
    )
    parser.add_argument(
        "--workers", type=int, default=1,
        help="Number of parallel threads per entity type (default: 1 = sequential).",
    )
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )

    config_path = Path(args.config)
    if not config_path.exists():
        log.error("Config file not found: %s", config_path)
        sys.exit(1)

    full_config = load_yaml(config_path)
    adapter_config = full_config.get(args.adapter, {})
    csv_files = full_config.get("csv_files", {})
    load_order = full_config.get("load_order", ["site", "olt", "splitter", "ont", "connection"])

    data_dir = Path(args.data_dir)
    if not data_dir.exists():
        log.error("Data directory not found: %s", data_dir)
        sys.exit(1)

    # Initialize adapter (only needed for actual loading)
    adapter = None
    if not args.dry_run:
        adapter = get_adapter(args.adapter)
        adapter.connect(adapter_config)
        if not adapter.health_check():
            log.error("Health check failed for %s", args.adapter)
            sys.exit(1)

        # Setup model (create types, roles, etc.)
        entity_mapping = adapter_config.get("entity_mapping", {})
        adapter.setup_model(entity_mapping)

    # Load entities in order
    id_mapping: dict[str, str] = {}
    results: dict[str, tuple[int, int]] = {}
    start_time = time.time()

    for entity_type in load_order:
        csv_file = csv_files.get(entity_type, f"{entity_type}s.csv")
        csv_path = data_dir / csv_file

        if not csv_path.exists():
            log.warning("CSV not found: %s (skipping %s)", csv_path, entity_type)
            continue

        rows = read_csv(csv_path)
        log.info("Loading %d %s records from %s", len(rows), entity_type, csv_path)

        if entity_type == "connection":
            # Pre-fetch all interfaces to avoid per-cable GET lookups
            if adapter is not None and hasattr(adapter, "prefetch_interfaces"):
                adapter.prefetch_interfaces()
            ok, err = load_connections(
                adapter, rows, id_mapping, args.dry_run, args.fail_fast,
                max_workers=args.workers,
            )
        else:
            parent_field = PARENT_FIELDS.get(entity_type)
            ok, err = load_entities(
                adapter, entity_type, rows, id_mapping,
                parent_field, args.dry_run, args.fail_fast,
                max_workers=args.workers,
            )
        results[entity_type] = (ok, err)

    # Create visualization (OSP view for Kuwaiba, topology info for NetBox)
    if adapter is not None and not args.dry_run:
        try:
            site_csv = data_dir / csv_files.get("site", "sites.csv")
            conn_csv = data_dir / csv_files.get("connection", "connections.csv")
            site_rows = read_csv(site_csv) if site_csv.exists() else []
            conn_rows = read_csv(conn_csv) if conn_csv.exists() else []
            # Load device CSVs for per-device geo-coordinates
            device_rows: dict[str, list[dict]] = {}
            for etype, default_file in [
                ("olt", "olts.csv"), ("splitter", "splitters.csv"), ("ont", "onts.csv"),
            ]:
                dev_csv = data_dir / csv_files.get(etype, default_file)
                if dev_csv.exists():
                    device_rows[etype] = read_csv(dev_csv)
            adapter.create_visualization(id_mapping, site_rows, conn_rows, device_rows)
        except Exception as e:
            log.warning("Visualization creation failed (non-fatal): %s", e)

    # Load service inventory (CFS/RFS) if service CSVs are present
    service_config = adapter_config.get("service_classes", {})
    has_service_csvs = (data_dir / "subscribers.csv").exists()
    if adapter is not None and not args.dry_run and service_config and has_service_csvs:
        if args.adapter == "kuwaiba":
            svc_results = load_services(
                adapter, data_dir, id_mapping, service_config, args.dry_run,
            )
            results.update(svc_results)
        elif args.adapter == "netbox":
            adapter.setup_service_model(service_config)
            svc_results = adapter.load_services(
                data_dir, id_mapping, service_config,
            )
            results.update(svc_results)
    elif args.dry_run and service_config and has_service_csvs:
        # Dry-run service summary (adapter-agnostic)
        svc_results = load_services(
            None, data_dir, id_mapping, service_config, True,
        )
        results.update(svc_results)

    elapsed = time.time() - start_time

    # Disconnect
    if adapter is not None:
        adapter.disconnect()

    # Print summary
    print_summary(results, elapsed)

    # Exit with error code if any failures
    total_errors = sum(err for _, err in results.values())
    if total_errors > 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
