#!/usr/bin/env python3
# =============================================================================
# netbox_adapter.py
# Generated by: target-loader-adapter | Date: 2026-02-19
# Purpose: NetBox REST adapter for loading GPON inventory data.
# Assumptions: NetBox v4.x, requests library, localhost:8000 Docker container.
# =============================================================================

"""NetBox REST adapter using requests.

Loads GPON entities into NetBox via the REST API. Creates manufacturers,
device types (with interface templates), device roles, sites, devices,
interfaces, and cables.
"""

import logging
import threading
from typing import Any

import requests

from base_adapter import BaseTargetAdapter

log = logging.getLogger(__name__)

ENDPOINT_MAP: dict[str, str] = {
    "site": "/api/dcim/sites/",
    "manufacturer": "/api/dcim/manufacturers/",
    "device_type": "/api/dcim/device-types/",
    "device_role": "/api/dcim/device-roles/",
    "device": "/api/dcim/devices/",
    "interface": "/api/dcim/interfaces/",
    "interface_template": "/api/dcim/interface-templates/",
    "cable": "/api/dcim/cables/",
    "ip_address": "/api/ipam/ip-addresses/",
    "custom_field": "/api/extras/custom-fields/",
    "tag": "/api/extras/tags/",
    "module_bay_template": "/api/dcim/module-bay-templates/",
    "module_bay": "/api/dcim/module-bays/",
    "module_type": "/api/dcim/module-types/",
    "module": "/api/dcim/modules/",
    "rack": "/api/dcim/racks/",
    "inventory_item": "/api/dcim/inventory-items/",
    "inventory_item_role": "/api/dcim/inventory-item-roles/",
}

# Interface type constants for GPON
INTERFACE_TYPES = {
    "gpon_port": "1000base-x-sfp",
    "pon_uplink": "10gbase-x-sfpp",
    "ont_pon": "1000base-x-sfp",
    "ont_lan": "1000base-t",
}


class NetBoxAdapter(BaseTargetAdapter):
    """Concrete adapter for NetBox v4.x REST API."""

    def __init__(self) -> None:
        self._base_url: str = ""
        self._headers: dict[str, str] = {}
        self._session: requests.Session | None = None
        self._config: dict = {}
        self._id_cache: dict[str, dict[str, int]] = {}  # e.g. {"manufacturer": {"Huawei": 1}}
        self._batch_size: int = 50
        self._device_site_map: dict[str, str] = {}  # device NetBox ID → site NetBox ID
        self._bay_device_map: dict[str, int] = {}  # module bay ID → device NetBox ID
        self._module_device_map: dict[str, int] = {}  # module ID → device NetBox ID
        self._interface_cache: dict[tuple[str, str], int] = {}  # (device_id, name) → iface_id
        self._lock = threading.Lock()  # protects shared maps

    # -- connection lifecycle ------------------------------------------------

    def connect(self, config: dict) -> None:
        """Configure base URL and auth token from config dict.

        Args:
            config: Must contain base_url, token. Optionally batch_size.
        """
        self._config = config
        self._base_url = config["base_url"].rstrip("/")
        self._headers = {
            "Authorization": f"Token {config['token']}",
            "Content-Type": "application/json",
            "Accept": "application/json",
        }
        self._batch_size = config.get("batch_size", 50)

        # Connection-pooled session with keep-alive
        self._session = requests.Session()
        self._session.headers.update(self._headers)
        adapter = requests.adapters.HTTPAdapter(
            pool_connections=20, pool_maxsize=20,
        )
        self._session.mount("http://", adapter)
        self._session.mount("https://", adapter)

        log.info("NetBox adapter configured for %s (pooled session)", self._base_url)

    def disconnect(self) -> None:
        """Close the pooled HTTP session."""
        if self._session is not None:
            self._session.close()
            self._session = None
        log.debug("disconnect() called — session closed")

    # -- health check --------------------------------------------------------

    def health_check(self) -> bool:
        """Check NetBox is responding by hitting the status endpoint (with auth)."""
        try:
            url = f"{self._base_url}/api/status/"
            resp = self._session.get(url, timeout=10)  # v4.x requires auth
            ok = resp.status_code == 200
            if ok:
                log.info("NetBox health check passed")
            else:
                log.warning("NetBox health check returned %d", resp.status_code)
            return ok
        except Exception as e:
            log.error("NetBox health check failed: %s", e)
            return False

    # -- model setup ---------------------------------------------------------

    def setup_model(self, model_def: dict[str, Any]) -> dict[str, str]:
        """Create custom fields, tags, manufacturers, device types, and roles.

        This sets up the GPON data model in NetBox so that devices can
        reference the correct types and roles.

        Returns:
            Mapping of logical names to NetBox IDs (as strings).
        """
        id_map: dict[str, str] = {}

        # Tag for migration tracking
        tag = self._get_or_create(
            ENDPOINT_MAP["tag"],
            {"name": "gpon-migration", "slug": "gpon-migration",
             "color": "2196f3", "description": "GPON migration demo data"},
            "slug", "gpon-migration",
        )
        id_map["tag:gpon-migration"] = str(tag["id"])

        # Custom fields
        # NetBox v4.x uses "object_types" (renamed from "content_types")
        for cf in [
            {"name": "source_id", "type": "text", "label": "Source ID",
             "object_types": ["dcim.device", "dcim.site"],
             "description": "Original ID from source system"},
            {"name": "serial_number", "type": "text", "label": "Serial Number",
             "object_types": ["dcim.device"],
             "description": "Equipment serial number"},
        ]:
            result = self._get_or_create(
                ENDPOINT_MAP["custom_field"], cf, "name", cf["name"]
            )
            id_map[f"cf:{cf['name']}"] = str(result["id"])

        # Manufacturers
        for mfr_name in ["Huawei", "Nokia", "ZTE", "Generic"]:
            slug = mfr_name.lower()
            mfr = self._get_or_create(
                ENDPOINT_MAP["manufacturer"],
                {"name": mfr_name, "slug": slug},
                "slug", slug,
            )
            self._cache_id("manufacturer", mfr_name, mfr["id"])
            id_map[f"mfr:{mfr_name}"] = str(mfr["id"])

        # Device roles
        for role_name, role_color in [("olt", "ff9800"), ("splitter", "4caf50"), ("ont", "2196f3")]:
            role = self._get_or_create(
                ENDPOINT_MAP["device_role"],
                {"name": role_name.upper(), "slug": role_name, "color": role_color},
                "slug", role_name,
            )
            self._cache_id("device_role", role_name, role["id"])
            id_map[f"role:{role_name}"] = str(role["id"])

        # OLT device types — use ModuleBayTemplates (slots) instead of direct interfaces
        # Chassis slot definitions per vendor (mirrored from value_pools.py to avoid
        # cross-directory import — netbox_adapter runs from the load/ directory)
        olt_chassis = {
            "Huawei": {
                "service_slots": list(range(1, 16)),   # 1-15
                "control_slots": [16, 17],
            },
            "Nokia": {
                "service_slots": list(range(1, 17)),   # 1-16
                "control_slots": [17, 18],
            },
            "ZTE": {
                "service_slots": list(range(1, 16)),   # 1-15
                "control_slots": [16, 17],
            },
        }

        # GPON card ModuleType definitions per vendor
        gpon_card_models = [
            {"manufacturer": "Huawei", "model": "H901GPHF", "slug": "h901gphf", "ports": 16},
            {"manufacturer": "Huawei", "model": "H901GPUF", "slug": "h901gpuf", "ports": 16},
            {"manufacturer": "Huawei", "model": "H901GPSF", "slug": "h901gpsf", "ports": 16},
            {"manufacturer": "Nokia", "model": "FGLT-B", "slug": "fglt-b", "ports": 16},
            {"manufacturer": "Nokia", "model": "NGLT-A", "slug": "nglt-a", "ports": 8},
            {"manufacturer": "ZTE", "model": "GFGL", "slug": "gfgl", "ports": 16},
            {"manufacturer": "ZTE", "model": "GFGN", "slug": "gfgn", "ports": 16},
        ]

        # Control card ModuleType definitions per vendor
        control_card_models = [
            {"manufacturer": "Huawei", "model": "H901MPLA", "slug": "h901mpla", "ports": 4},
            {"manufacturer": "Nokia", "model": "FANT-F", "slug": "fant-f", "ports": 4},
            {"manufacturer": "ZTE", "model": "SFUH", "slug": "sfuh", "ports": 4},
        ]

        olt_device_types = [
            {"manufacturer": "Huawei", "model": "MA5800-X15", "slug": "ma5800-x15", "u_height": 6},
            {"manufacturer": "Nokia", "model": "ISAM-FX16", "slug": "isam-fx16", "u_height": 5},
            {"manufacturer": "ZTE", "model": "C600", "slug": "c600", "u_height": 4},
        ]

        for dt_def in olt_device_types:
            mfr_id = self._get_cached_id("manufacturer", dt_def["manufacturer"])
            dt = self._get_or_create(
                ENDPOINT_MAP["device_type"],
                {"manufacturer": mfr_id, "model": dt_def["model"],
                 "slug": dt_def["slug"], "u_height": dt_def["u_height"]},
                "slug", dt_def["slug"],
            )
            self._cache_id("device_type", dt_def["model"], dt["id"])
            id_map[f"dt:{dt_def['model']}"] = str(dt["id"])

            # Create ModuleBayTemplates for all possible slot positions
            chassis = olt_chassis[dt_def["manufacturer"]]
            all_positions = sorted(chassis["service_slots"] + chassis["control_slots"])
            for pos in all_positions:
                self._get_or_create(
                    ENDPOINT_MAP["module_bay_template"],
                    {"device_type": dt["id"], "name": f"Slot {pos}", "position": str(pos)},
                    "name", f"Slot {pos}",
                    extra_filter=f"&device_type_id={dt['id']}",
                )

        # Non-OLT device types with direct interface templates
        other_device_types = [
            {"manufacturer": "Generic", "model": "Splitter-1xN", "slug": "splitter-1xn",
             "interfaces": [("input", INTERFACE_TYPES["ont_pon"], 1),
                            ("output-{i}", INTERFACE_TYPES["ont_pon"], 32)]},
            {"manufacturer": "Huawei", "model": "HG8245H", "slug": "hg8245h",
             "interfaces": [("pon", INTERFACE_TYPES["ont_pon"], 1),
                            ("lan-{i}", INTERFACE_TYPES["ont_lan"], 4)]},
            {"manufacturer": "Huawei", "model": "HG8546M", "slug": "hg8546m",
             "interfaces": [("pon", INTERFACE_TYPES["ont_pon"], 1),
                            ("lan-{i}", INTERFACE_TYPES["ont_lan"], 4)]},
            {"manufacturer": "ZTE", "model": "F660", "slug": "f660",
             "interfaces": [("pon", INTERFACE_TYPES["ont_pon"], 1),
                            ("lan-{i}", INTERFACE_TYPES["ont_lan"], 4)]},
            {"manufacturer": "Nokia", "model": "I-010G-Q", "slug": "i-010g-q",
             "interfaces": [("pon", INTERFACE_TYPES["ont_pon"], 1),
                            ("lan-{i}", INTERFACE_TYPES["ont_lan"], 1)]},
        ]

        for dt_def in other_device_types:
            mfr_id = self._get_cached_id("manufacturer", dt_def["manufacturer"])
            dt = self._get_or_create(
                ENDPOINT_MAP["device_type"],
                {"manufacturer": mfr_id, "model": dt_def["model"], "slug": dt_def["slug"]},
                "slug", dt_def["slug"],
            )
            self._cache_id("device_type", dt_def["model"], dt["id"])
            id_map[f"dt:{dt_def['model']}"] = str(dt["id"])

            for name_tpl, iface_type, count in dt_def["interfaces"]:
                for idx in range(1, count + 1):
                    iface_name = name_tpl.format(i=idx) if "{i}" in name_tpl else name_tpl
                    self._get_or_create(
                        ENDPOINT_MAP["interface_template"],
                        {"device_type": dt["id"], "name": iface_name, "type": iface_type},
                        "name", iface_name,
                        extra_filter=f"&device_type_id={dt['id']}",
                    )

        # Module types for GPON and control line cards
        for mt_def in gpon_card_models:
            mfr_id = self._get_cached_id("manufacturer", mt_def["manufacturer"])
            mt = self._get_or_create(
                ENDPOINT_MAP["module_type"],
                {"manufacturer": mfr_id, "model": mt_def["model"]},
                "model", mt_def["model"],
            )
            self._cache_id("module_type", mt_def["model"], mt["id"])
            id_map[f"mt:{mt_def['model']}"] = str(mt["id"])

            # Interface templates on module type: 0/{module}/{port}
            for port_idx in range(1, mt_def["ports"] + 1):
                iface_name = "0/{module}/" + str(port_idx)
                self._get_or_create(
                    ENDPOINT_MAP["interface_template"],
                    {"module_type": mt["id"], "name": iface_name,
                     "type": INTERFACE_TYPES["gpon_port"]},
                    "name", iface_name,
                    extra_filter=f"&module_type_id={mt['id']}",
                )

        for mt_def in control_card_models:
            mfr_id = self._get_cached_id("manufacturer", mt_def["manufacturer"])
            mt = self._get_or_create(
                ENDPOINT_MAP["module_type"],
                {"manufacturer": mfr_id, "model": mt_def["model"]},
                "model", mt_def["model"],
            )
            self._cache_id("module_type", mt_def["model"], mt["id"])
            id_map[f"mt:{mt_def['model']}"] = str(mt["id"])

            for port_idx in range(1, mt_def["ports"] + 1):
                iface_name = f"uplink-{port_idx}"
                self._get_or_create(
                    ENDPOINT_MAP["interface_template"],
                    {"module_type": mt["id"], "name": iface_name,
                     "type": INTERFACE_TYPES["pon_uplink"]},
                    "name", iface_name,
                    extra_filter=f"&module_type_id={mt['id']}",
                )

        # Inventory item role for SFP transceivers
        sfp_role = self._get_or_create(
            ENDPOINT_MAP["inventory_item_role"],
            {"name": "SFP Transceiver", "slug": "sfp-transceiver", "color": "ff9800"},
            "slug", "sfp-transceiver",
        )
        self._cache_id("inventory_item_role", "sfp-transceiver", sfp_role["id"])
        id_map["role:sfp-transceiver"] = str(sfp_role["id"])

        log.info("NetBox model setup complete: %d items", len(id_map))
        return id_map

    # -- object CRUD ---------------------------------------------------------

    def create_object(
        self, class_name: str, parent_id: str, attributes: dict[str, Any]
    ) -> str:
        """Create a single object in NetBox.

        Args:
            class_name: Entity type (site, olt, slot, line_card, splitter,
                        sfp_transceiver, ont).
            parent_id: NetBox parent ID (site ID for OLTs, device ID for
                       slots/cards, etc.).
            attributes: Object attributes.

        Returns:
            NetBox object ID as string.
        """
        if class_name == "site":
            return self._create_site(attributes)
        elif class_name == "rack":
            return self._create_rack(parent_id, attributes)
        elif class_name == "slot":
            return self._create_slot(parent_id, attributes)
        elif class_name == "line_card":
            return self._create_line_card(parent_id, attributes)
        elif class_name == "sfp_transceiver":
            return self._create_sfp_transceiver(parent_id, attributes)
        else:
            return self._create_device(class_name, parent_id, attributes)

    def _create_site(self, attributes: dict[str, Any]) -> str:
        """Create a NetBox site."""
        site_id = attributes.get("site_id", "")
        payload = {
            "name": attributes.get("site_name", site_id),
            "slug": site_id.lower().replace(" ", "-"),
            "status": "active" if attributes.get("status") == "ACTIVE" else "planned",
            "latitude": attributes.get("latitude"),
            "longitude": attributes.get("longitude"),
            "custom_fields": {"source_id": site_id},
            "tags": [{"name": "gpon-migration"}],
        }
        result = self._get_or_create(
            ENDPOINT_MAP["site"], payload, "slug", payload["slug"]
        )
        log.info("Created site '%s' id=%s", payload["name"], result["id"])
        return str(result["id"])

    def _create_rack(self, parent_id: str, attributes: dict[str, Any]) -> str:
        """Create a NetBox rack."""
        rack_id = attributes.get("rack_id", "")
        rack_name = attributes.get("rack_name", rack_id)
        u_height = int(attributes.get("u_height", 42))
        payload = {
            "name": rack_name,
            "site": int(parent_id),
            "status": "active",
            "u_height": u_height,
            "tags": [{"name": "gpon-migration"}],
        }
        result = self._get_or_create(
            ENDPOINT_MAP["rack"], payload, "name", rack_name,
            extra_filter=f"&site_id={parent_id}",
        )
        nb_id = str(result["id"])
        # Cache CSV rack_id → NetBox ID for device placement
        if not hasattr(self, "_rack_map"):
            self._rack_map: dict[str, str] = {}
        with self._lock:
            self._rack_map[rack_id] = nb_id
        log.info("Created rack '%s' id=%s (site=%s)", rack_name, nb_id, parent_id)
        return nb_id

    def _create_device(
        self, class_name: str, parent_id: str, attributes: dict[str, Any]
    ) -> str:
        """Create a NetBox device (OLT, splitter, or ONT).

        For OLTs, parent_id is a site NetBox ID directly.
        For splitters/ONTs, parent_id is a device NetBox ID — the
        site is resolved via _device_site_map.
        """
        source_id = attributes.get(f"{class_name}_id", attributes.get("ont_id", ""))
        name = source_id

        # Resolve site: OLTs get site directly; splitters/ONTs inherit from parent device
        if class_name == "olt":
            site_id = parent_id  # parent_id is already a site NetBox ID
        else:
            with self._lock:
                site_id = self._device_site_map.get(parent_id, parent_id)

        # Resolve device type
        if class_name == "splitter":
            dt_id = self._get_cached_id("device_type", "Splitter-1xN")
        else:
            model = attributes.get("model", attributes.get("ont_model", ""))
            dt_id = self._get_cached_id("device_type", model)

        role_id = self._get_cached_id("device_role", class_name)

        status_map = {
            "IN_SERVICE": "active", "ACTIVE": "active",
            "MAINTENANCE": "planned", "SUSPENDED": "offline",
            "INACTIVE": "decommissioning",
        }
        status = status_map.get(attributes.get("status", "ACTIVE"), "active")

        payload = {
            "name": name,
            "device_type": dt_id,
            "role": role_id,
            "site": int(site_id),
            "status": status,
            "serial": attributes.get("serial", attributes.get("serial_number", "")),
            "custom_fields": {"source_id": source_id},
            "tags": [{"name": "gpon-migration"}],
        }

        # Add rack placement for OLTs with rack_id
        rack_id_csv = attributes.get("rack_id", "")
        if rack_id_csv:
            with self._lock:
                rack_nb_id = getattr(self, "_rack_map", {}).get(rack_id_csv)
            if rack_nb_id:
                payload["rack"] = int(rack_nb_id)
                rack_pos = attributes.get("rack_position", "")
                if rack_pos:
                    payload["position"] = int(rack_pos)
                    payload["face"] = "front"

        resp = self._post(ENDPOINT_MAP["device"], payload)
        device_id = str(resp["id"])
        # Track which site this device belongs to
        with self._lock:
            self._device_site_map[device_id] = site_id
        log.info("Created %s '%s' id=%s (site=%s)", class_name, name, device_id, site_id)
        return device_id

    def _create_slot(self, parent_id: str, attributes: dict[str, Any]) -> str:
        """Find the auto-created ModuleBay on the OLT device by slot position.

        ModuleBays are auto-created when the OLT device is created from
        a DeviceType that has ModuleBayTemplates. We look up the bay by
        its position field matching the slot_number from the CSV.
        """
        slot_number = attributes.get("slot_number", "")
        url = (
            f"{self._base_url}{ENDPOINT_MAP['module_bay']}"
            f"?device_id={parent_id}&position={slot_number}"
        )
        resp = self._session.get(url, timeout=30)
        resp.raise_for_status()
        results = resp.json().get("results", [])
        if results:
            bay_id = str(results[0]["id"])
            device_id = results[0]["device"]["id"]
            log.info("Found ModuleBay slot %s on device %s, bay_id=%s",
                     slot_number, parent_id, bay_id)
            # Track bay→device and device→site for later lookups
            with self._lock:
                self._bay_device_map[bay_id] = device_id
                if parent_id in self._device_site_map:
                    self._device_site_map[bay_id] = self._device_site_map[parent_id]
            return bay_id
        raise ValueError(
            f"ModuleBay not found for device={parent_id} position={slot_number}"
        )

    def _create_line_card(self, parent_id: str, attributes: dict[str, Any]) -> str:
        """Install a Module (line card) into a ModuleBay.

        The ModuleBay ID comes from the slot creation step. Installing a
        module of the correct ModuleType auto-creates interfaces from the
        ModuleType's InterfaceTemplates.
        """
        card_model = attributes.get("card_model", "")
        mt_id = self._get_cached_id("module_type", card_model)
        if not mt_id:
            raise ValueError(f"ModuleType not found for card model: {card_model}")

        # Resolve device ID from module bay
        with self._lock:
            device_id = self._bay_device_map.get(parent_id)
        if not device_id:
            raise ValueError(f"Device not found for module bay: {parent_id}")

        payload = {
            "device": device_id,
            "module_bay": int(parent_id),
            "module_type": mt_id,
            "serial": attributes.get("serial", ""),
            "tags": [{"name": "gpon-migration"}],
        }

        resp = self._post(ENDPOINT_MAP["module"], payload)
        module_id = str(resp["id"])
        # Track module→device and site for this module
        with self._lock:
            self._module_device_map[module_id] = device_id
            self._device_site_map[module_id] = self._device_site_map.get(str(device_id), "")
        log.info("Installed module '%s' (type=%s) into bay %s, module_id=%s",
                 card_model, mt_id, parent_id, module_id)
        return module_id

    def _create_sfp_transceiver(self, parent_id: str, attributes: dict[str, Any]) -> str:
        """Create an InventoryItem for an SFP transceiver on a device.

        The parent_id here is the module ID (from line_card creation).
        We resolve the device_id from the cached module→device map.
        """
        sfp_class = attributes.get("sfp_class", "")
        port_name = attributes.get("port_name", "")
        sfp_id = attributes.get("sfp_id", "")

        # Resolve device from cached module→device map (avoids per-SFP GET)
        with self._lock:
            device_id = self._module_device_map.get(parent_id)
        if not device_id:
            # Fallback: GET module to find device
            url = f"{self._base_url}{ENDPOINT_MAP['module']}{parent_id}/"
            resp = self._session.get(url, timeout=30)
            resp.raise_for_status()
            device_id = resp.json().get("device", {}).get("id", "")
        if not device_id:
            raise ValueError(f"Device not found for module {parent_id}")

        role_id = self._get_cached_id("inventory_item_role", "sfp-transceiver")

        payload = {
            "device": int(device_id),
            "name": f"SFP {sfp_class} ({port_name})",
            "role": role_id,
            "label": sfp_id,
            "description": f"Class: {sfp_class} | Wavelength: {attributes.get('wavelength', '')}",
            "tags": [{"name": "gpon-migration"}],
        }

        resp_post = self._post(ENDPOINT_MAP["inventory_item"], payload)
        item_id = str(resp_post["id"])
        log.info("Created SFP transceiver '%s' on device %s, item_id=%s",
                 sfp_id, device_id, item_id)
        return item_id

    def bulk_create(
        self, class_name: str, objects: list[dict[str, Any]]
    ) -> list[str]:
        """Create objects in batches using NetBox's native bulk API.

        NetBox accepts JSON arrays for bulk creation. Objects are posted
        in batches of batch_size (default 50).
        """
        all_ids: list[str] = []
        for i in range(0, len(objects), self._batch_size):
            batch = objects[i : i + self._batch_size]
            # For devices, we need to build payloads individually
            for obj in batch:
                parent_id = obj.pop("_parent_id", "")
                obj_id = self.create_object(class_name, parent_id, obj)
                all_ids.append(obj_id)
        return all_ids

    # -- connections ---------------------------------------------------------

    def create_connection(
        self,
        a_endpoint_id: str,
        a_port: str,
        b_endpoint_id: str,
        b_port: str,
        connection_type: str,
    ) -> str:
        """Create a Cable between two device interfaces.

        Args:
            a_endpoint_id: NetBox device ID for A-side.
            a_port: Interface name on A-side device.
            b_endpoint_id: NetBox device ID for B-side.
            b_port: Interface name on B-side device.
            connection_type: Cable type (default: smf).

        Returns:
            Cable ID as string.
        """
        # Resolve interface IDs
        a_iface_id = self._find_interface(a_endpoint_id, a_port)
        b_iface_id = self._find_interface(b_endpoint_id, b_port)

        if not a_iface_id or not b_iface_id:
            log.warning(
                "Could not resolve interfaces for cable: %s:%s ↔ %s:%s",
                a_endpoint_id, a_port, b_endpoint_id, b_port,
            )
            return ""

        payload = {
            "a_terminations": [{"object_type": "dcim.interface", "object_id": a_iface_id}],
            "b_terminations": [{"object_type": "dcim.interface", "object_id": b_iface_id}],
            "type": connection_type or "smf",
            "status": "connected",
        }

        try:
            resp = self._post(ENDPOINT_MAP["cable"], payload)
            log.info("Created cable %s:%s ↔ %s:%s id=%s",
                     a_endpoint_id, a_port, b_endpoint_id, b_port, resp["id"])
            return str(resp["id"])
        except requests.HTTPError as e:
            if e.response is not None and e.response.status_code == 409:
                log.warning("Cable already exists: %s:%s ↔ %s:%s (idempotent skip)",
                            a_endpoint_id, a_port, b_endpoint_id, b_port)
                return ""
            raise

    def prefetch_interfaces(self) -> int:
        """Batch-fetch all interfaces tagged gpon-migration and cache them.

        Call this once before loading connections to avoid per-cable GET lookups.
        Returns the number of interfaces cached.
        """
        self._interface_cache.clear()
        url = (
            f"{self._base_url}{ENDPOINT_MAP['interface']}"
            f"?limit=1000"
        )
        total = 0
        while url:
            resp = self._session.get(url, timeout=60)
            resp.raise_for_status()
            data = resp.json()
            for iface in data.get("results", []):
                device_id = str(iface.get("device", {}).get("id", ""))
                name = iface.get("name", "")
                if device_id and name:
                    self._interface_cache[(device_id, name)] = iface["id"]
                    total += 1
            url = data.get("next")
        log.info("Pre-fetched %d interfaces into cache", total)
        return total

    def _find_interface(self, device_id: str, interface_name: str) -> int | None:
        """Look up a device interface by name, using pre-fetched cache."""
        cached = self._interface_cache.get((device_id, interface_name))
        if cached is not None:
            return cached

        # Fallback to API lookup on cache miss
        url = (
            f"{self._base_url}{ENDPOINT_MAP['interface']}"
            f"?device_id={device_id}&name={interface_name}"
        )
        resp = self._session.get(url, timeout=30)
        resp.raise_for_status()
        results = resp.json().get("results", [])
        if results:
            iface_id = results[0]["id"]
            self._interface_cache[(device_id, interface_name)] = iface_id
            return iface_id
        log.warning("Interface not found: device=%s name=%s", device_id, interface_name)
        return None

    # -- bulk creation -------------------------------------------------------

    # Only bulk for lightweight entities — devices and modules trigger heavy
    # server-side interface template expansion that's faster with per-item
    # threaded POSTs across multiple Django/gunicorn workers.
    BULK_ENTITY_TYPES = {"site", "sfp_transceiver"}

    # Per-endpoint batch sizes: devices with interface templates are heavier,
    # so use smaller batches to avoid long transactions.
    _BULK_BATCH_SIZES: dict[str, int] = {
        "/api/dcim/devices/": 10,       # heavy: interface template expansion
        "/api/dcim/modules/": 10,       # heavy: interface template expansion
        "/api/dcim/cables/": 50,        # lightweight
        "/api/dcim/sites/": 50,         # lightweight
        "/api/dcim/inventory-items/": 50,  # lightweight
    }

    def _bulk_post(self, endpoint: str, payloads: list[dict]) -> list[dict]:
        """POST JSON arrays to a NetBox endpoint in batches.

        Falls back to per-item POST if a batch fails (NetBox bulk is atomic).
        Batch size is tuned per endpoint type.
        """
        batch_size = self._BULK_BATCH_SIZES.get(endpoint, self._batch_size)
        results: list[dict] = []
        total_batches = (len(payloads) + batch_size - 1) // batch_size
        for i in range(0, len(payloads), batch_size):
            batch = payloads[i : i + batch_size]
            batch_num = i // self._batch_size + 1
            url = f"{self._base_url}{endpoint}"
            resp = self._session.post(url, json=batch, timeout=120)
            if resp.ok:
                batch_results = resp.json()
                if isinstance(batch_results, list):
                    results.extend(batch_results)
                else:
                    results.append(batch_results)
                log.info("Bulk POST %s batch %d/%d: %d items OK",
                         endpoint, batch_num, total_batches, len(batch))
            else:
                log.warning(
                    "Bulk POST %s batch %d/%d failed (HTTP %d), falling back to per-item",
                    endpoint, batch_num, total_batches, resp.status_code,
                )
                for payload in batch:
                    results.append(self._post(endpoint, payload))
        return results

    def create_objects_bulk(
        self, class_name: str, items: list[tuple[str, str, dict]]
    ) -> dict[str, str]:
        """Bulk-create objects using NetBox's array POST API.

        Args:
            class_name: Entity type (site, olt, splitter, ont, line_card,
                        sfp_transceiver).
            items: List of (source_id, parent_target_id, attributes).

        Returns:
            Mapping of source_id → target_id.
        """
        if class_name == "site":
            return self._bulk_create_sites(items)
        elif class_name == "line_card":
            return self._bulk_create_line_cards(items)
        elif class_name == "sfp_transceiver":
            return self._bulk_create_sfps(items)
        elif class_name in ("olt", "splitter", "ont"):
            return self._bulk_create_devices(class_name, items)
        raise ValueError(f"Bulk not supported for {class_name}")

    def _bulk_create_sites(
        self, items: list[tuple[str, str, dict]]
    ) -> dict[str, str]:
        payloads = []
        slug_to_source: dict[str, str] = {}  # slug → source_id
        for source_id, _, attrs in items:
            slug = source_id.lower().replace(" ", "-")
            payloads.append({
                "name": attrs.get("site_name", source_id),
                "slug": slug,
                "status": "active" if attrs.get("status") == "ACTIVE" else "planned",
                "latitude": attrs.get("latitude"),
                "longitude": attrs.get("longitude"),
                "custom_fields": {"source_id": source_id},
                "tags": [{"name": "gpon-migration"}],
            })
            slug_to_source[slug] = source_id
        results = self._bulk_post(ENDPOINT_MAP["site"], payloads)
        mapping: dict[str, str] = {}
        # Match by slug instead of position — NetBox bulk response order is
        # not guaranteed to match the input order.
        for resp in results:
            slug = resp.get("slug", "")
            source_id = slug_to_source.get(slug, "")
            if source_id:
                mapping[source_id] = str(resp["id"])
        log.info("Bulk-created %d sites", len(mapping))
        return mapping

    def _bulk_create_devices(
        self, class_name: str, items: list[tuple[str, str, dict]]
    ) -> dict[str, str]:
        status_map = {
            "IN_SERVICE": "active", "ACTIVE": "active",
            "MAINTENANCE": "planned", "SUSPENDED": "offline",
            "INACTIVE": "decommissioning",
        }
        payloads = []
        name_to_site: dict[str, str] = {}  # device name → site_id
        for source_id, parent_id, attrs in items:
            site_id = self._device_site_map.get(parent_id, parent_id)
            if class_name == "splitter":
                dt_id = self._get_cached_id("device_type", "Splitter-1xN")
            else:
                model = attrs.get("model", attrs.get("ont_model", ""))
                dt_id = self._get_cached_id("device_type", model)
            role_id = self._get_cached_id("device_role", class_name)
            status = status_map.get(attrs.get("status", "ACTIVE"), "active")
            dev_payload = {
                "name": source_id,
                "device_type": dt_id,
                "role": role_id,
                "site": int(site_id),
                "status": status,
                "serial": attrs.get("serial", attrs.get("serial_number", "")),
                "custom_fields": {"source_id": source_id},
                "tags": [{"name": "gpon-migration"}],
            }
            # Add rack placement if available
            rack_id_csv = attrs.get("rack_id", "")
            if rack_id_csv:
                rack_nb_id = getattr(self, "_rack_map", {}).get(rack_id_csv)
                if rack_nb_id:
                    dev_payload["rack"] = int(rack_nb_id)
                    rack_pos = attrs.get("rack_position", "")
                    if rack_pos:
                        dev_payload["position"] = int(rack_pos)
                        dev_payload["face"] = "front"
            payloads.append(dev_payload)
            name_to_site[source_id] = site_id
        results = self._bulk_post(ENDPOINT_MAP["device"], payloads)
        mapping: dict[str, str] = {}
        # Match by name instead of position — bulk response order not guaranteed
        for resp in results:
            name = resp.get("name", "")
            device_id = str(resp["id"])
            if name in name_to_site:
                mapping[name] = device_id
                self._device_site_map[device_id] = name_to_site[name]
        log.info("Bulk-created %d %ss", len(mapping), class_name)
        return mapping

    def _bulk_create_line_cards(
        self, items: list[tuple[str, str, dict]]
    ) -> dict[str, str]:
        payloads = []
        bay_to_source: dict[int, tuple[str, int]] = {}  # bay_id → (source_id, device_id)
        for source_id, parent_id, attrs in items:
            card_model = attrs.get("card_model", "")
            mt_id = self._get_cached_id("module_type", card_model)
            if not mt_id:
                raise ValueError(f"ModuleType not found for card model: {card_model}")
            device_id = self._bay_device_map.get(parent_id)
            if not device_id:
                raise ValueError(f"Device not found for module bay: {parent_id}")
            bay_int = int(parent_id)
            payloads.append({
                "device": device_id,
                "module_bay": bay_int,
                "module_type": mt_id,
                "serial": attrs.get("serial", ""),
                "tags": [{"name": "gpon-migration"}],
            })
            bay_to_source[bay_int] = (source_id, device_id)
        results = self._bulk_post(ENDPOINT_MAP["module"], payloads)
        mapping: dict[str, str] = {}
        # Match by module_bay instead of position — bulk response order not guaranteed
        for resp in results:
            bay_id = resp.get("module_bay", {}).get("id") if isinstance(resp.get("module_bay"), dict) else resp.get("module_bay")
            if bay_id and bay_id in bay_to_source:
                source_id, device_id = bay_to_source[bay_id]
                module_id = str(resp["id"])
                mapping[source_id] = module_id
                self._module_device_map[module_id] = device_id
                self._device_site_map[module_id] = self._device_site_map.get(str(device_id), "")
        log.info("Bulk-created %d line cards (modules)", len(mapping))
        return mapping

    def _bulk_create_sfps(
        self, items: list[tuple[str, str, dict]]
    ) -> dict[str, str]:
        role_id = self._get_cached_id("inventory_item_role", "sfp-transceiver")
        payloads = []
        for source_id, parent_id, attrs in items:
            device_id = self._module_device_map.get(parent_id)
            if not device_id:
                url = f"{self._base_url}{ENDPOINT_MAP['module']}{parent_id}/"
                resp = self._session.get(url, timeout=30)
                resp.raise_for_status()
                device_id = resp.json().get("device", {}).get("id", "")
            if not device_id:
                raise ValueError(f"Device not found for module {parent_id}")
            sfp_class = attrs.get("sfp_class", "")
            port_name = attrs.get("port_name", "")
            payloads.append({
                "device": int(device_id),
                "name": f"SFP {sfp_class} ({port_name})",
                "role": role_id,
                "label": source_id,
                "description": f"Class: {sfp_class} | Wavelength: {attrs.get('wavelength', '')}",
                "tags": [{"name": "gpon-migration"}],
            })
        results = self._bulk_post(ENDPOINT_MAP["inventory_item"], payloads)
        mapping: dict[str, str] = {}
        # Match by label (=source_id) instead of position
        for resp in results:
            label = resp.get("label", "")
            if label:
                mapping[label] = str(resp["id"])
        log.info("Bulk-created %d SFP transceivers", len(mapping))
        return mapping

    def create_connections_bulk(
        self, items: list[tuple[str, str, str, str, str, str]]
    ) -> dict[str, str]:
        """Bulk-create cables.

        Args:
            items: List of (conn_id, a_id, a_port, b_id, b_port, conn_type).

        Returns:
            Mapping of connection_id → cable_id.
        """
        payloads = []
        conn_ids = []
        skipped = 0
        for conn_id, a_id, a_port, b_id, b_port, conn_type in items:
            a_iface_id = self._find_interface(a_id, a_port)
            b_iface_id = self._find_interface(b_id, b_port)
            if not a_iface_id or not b_iface_id:
                log.warning("Skipping connection %s: interface not found", conn_id)
                skipped += 1
                continue
            payloads.append({
                "a_terminations": [{"object_type": "dcim.interface", "object_id": a_iface_id}],
                "b_terminations": [{"object_type": "dcim.interface", "object_id": b_iface_id}],
                "type": conn_type or "smf",
                "status": "connected",
            })
            conn_ids.append(conn_id)
        if skipped:
            log.warning("Skipped %d connections due to missing interfaces", skipped)
        results = self._bulk_post(ENDPOINT_MAP["cable"], payloads)
        mapping: dict[str, str] = {}
        for conn_id, resp in zip(conn_ids, results):
            mapping[conn_id] = str(resp["id"])
        log.info("Bulk-created %d cables", len(mapping))
        return mapping

    # -- visualization -------------------------------------------------------

    def create_visualization(
        self,
        _id_mapping: dict[str, str],
        _site_rows: list[dict],
        _connection_rows: list[dict],
        _device_rows: dict[str, list[dict]] | None = None,
    ) -> None:
        """Log topology plugin instructions.

        NetBox topology visualization is provided by the netbox-topology-views
        plugin, which auto-renders from existing Cable data. No additional API
        calls are needed — the plugin reads devices, cables, and roles directly.

        The plugin must be installed in the NetBox Docker image. See
        scripts/netbox-custom/Dockerfile and scripts/docker-compose.netbox.yml.
        """
        # Count cables via API
        cable_count = 0
        try:
            url = f"{self._base_url}{ENDPOINT_MAP['cable']}?limit=1"
            resp = self._session.get(url, timeout=10)
            if resp.ok:
                cable_count = resp.json().get("count", 0)
        except Exception:
            pass

        log.info(
            "NetBox topology visualization is available via the "
            "netbox-topology-views plugin. Navigate to: "
            "Plugins → Topology Views in the NetBox menu. "
            "All %d cables are already visible in the topology.",
            cable_count,
        )

        # Verify the plugin is installed
        try:
            url = f"{self._base_url}/api/plugins/"
            resp = self._session.get(url, timeout=10)
            if resp.ok:
                plugins = resp.json()
                # /api/plugins/ returns a dict with plugin names as keys
                plugin_keys = plugins.keys() if isinstance(plugins, dict) else []
                if any("topology" in k for k in plugin_keys):
                    log.info("netbox-topology-views plugin is installed and active")
                else:
                    log.warning(
                        "netbox-topology-views plugin not detected. "
                        "Rebuild the NetBox Docker image with: "
                        "docker compose -f scripts/docker-compose.netbox.yml build"
                    )
        except Exception:
            log.debug("Could not check plugin status (non-critical)")

    # -- verification --------------------------------------------------------

    def verify_load(self, class_name: str, expected_count: int) -> bool:
        """GET with ?limit=1 and compare the 'count' field."""
        endpoint = ENDPOINT_MAP.get(class_name, ENDPOINT_MAP["device"])
        # For device subtypes, filter by role
        extra = ""
        if class_name in ("olt", "splitter", "ont"):
            role_id = self._get_cached_id("device_role", class_name)
            if role_id:
                extra = f"&role_id={role_id}"
            endpoint = ENDPOINT_MAP["device"]

        url = f"{self._base_url}{endpoint}?limit=1{extra}"
        resp = self._session.get(url, timeout=30)
        resp.raise_for_status()
        actual = resp.json().get("count", 0)
        ok = actual >= expected_count
        log.info("verify %s: expected=%d actual=%d pass=%s",
                 class_name, expected_count, actual, ok)
        return ok

    # -- service inventory (CFS/RFS via Custom Objects plugin) ---------------

    # Custom Objects API base path
    _CO_BASE = "/api/plugins/custom-objects"
    # NetBox core choice sets endpoint
    _CHOICE_SET_EP = "/api/extras/custom-field-choice-sets/"

    def setup_service_model(self, service_config: dict) -> None:
        """Create Custom Object types, choice sets, and fields for CFS/RFS.

        Uses the netbox-custom-objects plugin REST API together with
        NetBox core choice sets. Idempotent — safe to call on every run.
        """
        # --- Choice sets (NetBox core) ---
        self._service_status_cs = self._get_or_create_choice_set(
            "service_status",
            "Service lifecycle status",
            [["ordered", "Ordered"], ["provisioning", "Provisioning"],
             ["active", "Active"], ["suspended", "Suspended"],
             ["terminated", "Terminated"]],
        )
        self._service_tier_cs = self._get_or_create_choice_set(
            "service_tier",
            "Broadband service tier",
            [["basic_30_10", "Basic 30/10 Mbps"],
             ["standard_100_50", "Standard 100/50 Mbps"],
             ["premium_300_100", "Premium 300/100 Mbps"],
             ["ultra_1000_300", "Ultra 1000/300 Mbps"]],
        )

        # --- Custom Object Types ---
        # Names must be lowercase + underscores; slug is hyphenated
        self._co_subscriber = self._get_or_create_co_type(
            "gpon_subscriber", "gpon-subscriber",
            "GPON subscriber (one per ONT)",
        )
        self._co_cfs = self._get_or_create_co_type(
            "gpon_broadband_cfs", "gpon-broadband-cfs",
            "Customer-facing broadband service",
        )
        self._co_rfs = self._get_or_create_co_type(
            "gpon_access_rfs", "gpon-access-rfs",
            "Resource-facing PON path service",
        )

        # --- Fields on gpon_subscriber ---
        sub_id = self._co_subscriber["id"]
        self._ensure_co_field(sub_id, "subscriber_id", "text",
                              required=True, unique=True, primary=True)
        self._ensure_co_field(sub_id, "customer_name", "text", required=True)
        self._ensure_co_field(sub_id, "address", "text")
        self._ensure_co_field(sub_id, "contract_start", "date")
        self._ensure_co_field(sub_id, "status", "select",
                              choice_set_id=self._service_status_cs["id"])
        self._ensure_co_field(sub_id, "ont_device", "object",
                              object_app_label="dcim", object_model="device")

        # --- Fields on gpon_broadband_cfs ---
        # NOTE: Cross-type object FK fields (custom→custom) cause a bug in
        # the Custom Objects plugin (dynamic model doesn't register the FK).
        # Use integer fields to store raw PKs as a workaround.
        cfs_type_id = self._co_cfs["id"]
        self._ensure_co_field(cfs_type_id, "cfs_id", "text",
                              required=True, unique=True, primary=True)
        self._ensure_co_field(cfs_type_id, "subscriber_pk", "integer")
        self._ensure_co_field(cfs_type_id, "service_tier", "select",
                              choice_set_id=self._service_tier_cs["id"])
        self._ensure_co_field(cfs_type_id, "bandwidth_down_mbps", "integer")
        self._ensure_co_field(cfs_type_id, "bandwidth_up_mbps", "integer")
        self._ensure_co_field(cfs_type_id, "status", "select",
                              choice_set_id=self._service_status_cs["id"])

        # --- Fields on gpon_access_rfs ---
        rfs_type_id = self._co_rfs["id"]
        self._ensure_co_field(rfs_type_id, "rfs_id", "text",
                              required=True, unique=True, primary=True)
        self._ensure_co_field(rfs_type_id, "cfs_pk", "integer")
        self._ensure_co_field(rfs_type_id, "ont_device", "object",
                              object_app_label="dcim", object_model="device")
        self._ensure_co_field(rfs_type_id, "olt_device", "object",
                              object_app_label="dcim", object_model="device")
        self._ensure_co_field(rfs_type_id, "splitter_device", "object",
                              object_app_label="dcim", object_model="device")
        self._ensure_co_field(rfs_type_id, "vlan_id", "integer")
        self._ensure_co_field(rfs_type_id, "pon_path", "text")
        self._ensure_co_field(rfs_type_id, "status", "select",
                              choice_set_id=self._service_status_cs["id"])

        # Store instance endpoints (slug-based)
        self._co_sub_ep = f"{self._CO_BASE}/{self._co_subscriber['slug']}/"
        self._co_cfs_ep = f"{self._CO_BASE}/{self._co_cfs['slug']}/"
        self._co_rfs_ep = f"{self._CO_BASE}/{self._co_rfs['slug']}/"

        # The Custom Objects plugin caches dynamic Django models per worker
        # process. Fields added after type creation are not reflected until
        # workers restart. Force a restart via NGINX Unit control socket.
        self._restart_netbox_workers()

        log.info("Custom Objects service model setup complete")

    def _restart_netbox_workers(self) -> None:
        """Restart NGINX Unit application workers to refresh dynamic models.

        The Custom Objects plugin creates dynamic Django model classes when
        a type is first used. Adding fields via API afterward does not update
        the in-memory model. Restarting workers forces fresh model creation.
        """
        import subprocess as _sp
        import time as _time

        log.info("Restarting NetBox workers to apply dynamic model changes...")
        result = _sp.run(
            ["docker", "exec", "netbox", "curl", "-s", "--unix-socket",
             "/opt/unit/unit.sock",
             "http://localhost/control/applications/netbox/restart"],
            capture_output=True, text=True, timeout=10,
        )
        if result.returncode != 0:
            log.warning("Could not restart workers: %s", result.stderr)
            return

        # Wait for workers to come back
        for attempt in range(20):
            _time.sleep(1)
            try:
                resp = self._session.get(
                    f"{self._base_url}/api/status/", timeout=5)
                if resp.ok:
                    log.info("NetBox workers restarted successfully")
                    return
            except Exception:
                pass
        log.warning("NetBox did not respond after worker restart")

    def _get_or_create_choice_set(
        self, name: str, description: str,
        extra_choices: list[list[str]],
    ) -> dict:
        """Create or find a choice set in NetBox core."""
        return self._get_or_create(
            self._CHOICE_SET_EP,
            {"name": name, "description": description,
             "extra_choices": extra_choices},
            "name", name,
        )

    def _get_or_create_co_type(
        self, name: str, slug: str, description: str,
    ) -> dict:
        """Create or find a Custom Object type.

        The Custom Objects plugin's list API does not support query
        parameter filtering, so we fetch all types and filter client-side.
        """
        endpoint = f"{self._CO_BASE}/custom-object-types/"
        url = f"{self._base_url}{endpoint}?limit=100"
        resp = self._session.get(url, timeout=30)
        resp.raise_for_status()
        for t in resp.json().get("results", []):
            if t.get("slug") == slug:
                log.debug("Found existing CO type '%s' id=%s", slug, t["id"])
                return t
        payload = {"name": name, "slug": slug, "description": description}
        return self._post(endpoint, payload)

    def _ensure_co_field(
        self, co_type_id: int, name: str, field_type: str, *,
        required: bool = False, unique: bool = False,
        primary: bool = False,
        choice_set_id: int | None = None,
        object_app_label: str | None = None,
        object_model: str | None = None,
    ) -> dict:
        """Create a field on a Custom Object type if it doesn't exist."""
        endpoint = f"{self._CO_BASE}/custom-object-type-fields/"
        # The plugin's list API ignores query filters — fetch all fields
        # and filter client-side by both type ID and field name.
        url = f"{self._base_url}{endpoint}?limit=500"
        resp = self._session.get(url, timeout=30)
        resp.raise_for_status()
        for field in resp.json().get("results", []):
            if (field.get("custom_object_type") == co_type_id
                    and field.get("name") == name):
                return field
        payload: dict[str, Any] = {
            "custom_object_type": co_type_id,
            "name": name,
            "type": field_type,
            "required": required,
            "unique": unique,
        }
        if primary:
            payload["primary"] = True
        if choice_set_id is not None:
            payload["choice_set"] = choice_set_id
        if object_app_label and object_model:
            payload["app_label"] = object_app_label
            payload["model"] = object_model
        return self._post(endpoint, payload)

    def load_services(
        self,
        data_dir: "Path",
        id_mapping: dict[str, str],
        service_config: dict,
    ) -> dict[str, tuple[int, int]]:
        """Load CFS/RFS service inventory into NetBox via Custom Objects.

        Reads subscribers.csv, services_cfs.csv, services_rfs.csv and
        creates gpon_subscriber, gpon_broadband_cfs, gpon_access_rfs instances.
        Resource links are embedded as object fields on the RFS (no separate
        link table needed — Custom Objects supports direct FK references).
        """
        from pathlib import Path as _Path

        results: dict[str, tuple[int, int]] = {}
        data_dir = _Path(data_dir)

        sub_csv = data_dir / "subscribers.csv"
        cfs_csv = data_dir / "services_cfs.csv"
        rfs_csv = data_dir / "services_rfs.csv"

        if not sub_csv.exists():
            log.info("No subscribers.csv found — skipping NetBox service loading")
            return results

        import csv as _csv

        def _read(path: _Path) -> list[dict]:
            with open(path, newline="") as f:
                return list(_csv.DictReader(f))

        subscribers = _read(sub_csv)
        cfs_rows = _read(cfs_csv) if cfs_csv.exists() else []
        rfs_rows = _read(rfs_csv) if rfs_csv.exists() else []

        # Map CSV status to choice set values
        status_map = {"ACTIVE": "active", "SUSPENDED": "suspended",
                      "INACTIVE": "terminated", "ORDERED": "ordered"}
        # Map CSV service tier names to choice set slugs
        tier_map = {
            "GPON Basic 30/10": "basic_30_10",
            "GPON Standard 100/50": "standard_100_50",
            "GPON Premium 300/100": "premium_300_100",
            "GPON Ultra 1000/300": "ultra_1000_300",
        }

        def _obj_ref(pk: str | int | None) -> dict | None:
            """Wrap a PK as {"id": pk} for Custom Objects FK fields."""
            if pk is None:
                return None
            return {"id": int(pk)}

        # --- Create subscribers ---
        sub_ok, sub_err = 0, 0
        subscriber_co_map: dict[str, int] = {}

        for sub in subscribers:
            ont_device_id = id_mapping.get(sub["ont_id"])
            payload: dict[str, Any] = {
                "subscriber_id": sub["subscriber_id"],
                "customer_name": sub["customer_name"],
                "address": sub.get("address", ""),
                "contract_start": sub.get("contract_start") or None,
                "status": status_map.get(sub.get("status", "ACTIVE"), "active"),
            }
            if ont_device_id:
                payload["ont_device"] = _obj_ref(ont_device_id)
            try:
                resp = self._post(self._co_sub_ep, payload)
                subscriber_co_map[sub["subscriber_id"]] = resp["id"]
                sub_ok += 1
            except Exception as e:
                log.error("Failed to create subscriber %s: %s",
                          sub["subscriber_id"], e)
                sub_err += 1
        results["subscriber"] = (sub_ok, sub_err)

        # --- Create CFS ---
        cfs_ok, cfs_err = 0, 0
        cfs_co_map: dict[str, int] = {}

        for cfs in cfs_rows:
            sub_co_id = subscriber_co_map.get(cfs["subscriber_id"])
            payload: dict[str, Any] = {
                "cfs_id": cfs["cfs_id"],
                "service_tier": tier_map.get(cfs["service_tier"], cfs["service_tier"]),
                "bandwidth_down_mbps": int(cfs["bandwidth_down_mbps"]),
                "bandwidth_up_mbps": int(cfs["bandwidth_up_mbps"]),
                "status": status_map.get(cfs.get("status", "ACTIVE"), "active"),
            }
            if sub_co_id:
                payload["subscriber_pk"] = int(sub_co_id)
            try:
                resp = self._post(self._co_cfs_ep, payload)
                cfs_co_map[cfs["cfs_id"]] = resp["id"]
                cfs_ok += 1
            except Exception as e:
                log.error("Failed to create CFS %s: %s", cfs["cfs_id"], e)
                cfs_err += 1
        results["cfs"] = (cfs_ok, cfs_err)

        # --- Create RFS with embedded resource links ---
        rfs_ok, rfs_err = 0, 0

        for rfs in rfs_rows:
            cfs_co_id = cfs_co_map.get(rfs["cfs_id"])
            ont_device_id = id_mapping.get(rfs.get("ont_id", ""))

            # Parse pon_path to extract OLT and splitter IDs
            pon_path = rfs.get("pon_path", "")
            olt_id_src, spl_id_src = "", ""
            if "\u2192" in pon_path:
                parts = pon_path.split("\u2192")
                if len(parts) >= 2:
                    olt_id_src = parts[0].strip()
                    spl_id_src = parts[1].strip()

            olt_device_id = id_mapping.get(olt_id_src) if olt_id_src else None
            spl_device_id = id_mapping.get(spl_id_src) if spl_id_src else None

            payload: dict[str, Any] = {
                "rfs_id": rfs["rfs_id"],
                "vlan_id": int(rfs["vlan_id"]),
                "pon_path": pon_path,
                "status": status_map.get(rfs.get("status", "ACTIVE"), "active"),
            }
            if cfs_co_id:
                payload["cfs_pk"] = int(cfs_co_id)
            if ont_device_id:
                payload["ont_device"] = _obj_ref(ont_device_id)
            if olt_device_id:
                payload["olt_device"] = _obj_ref(olt_device_id)
            if spl_device_id:
                payload["splitter_device"] = _obj_ref(spl_device_id)

            try:
                resp = self._post(self._co_rfs_ep, payload)
                rfs_ok += 1
            except Exception as e:
                log.error("Failed to create RFS %s: %s", rfs["rfs_id"], e)
                rfs_err += 1
        results["rfs"] = (rfs_ok, rfs_err)

        log.info("NetBox service loading complete: %d subscribers, %d CFS, %d RFS",
                 sub_ok, cfs_ok, rfs_ok)
        return results

    # -- internal helpers ----------------------------------------------------

    def _post(self, endpoint: str, payload: Any) -> Any:
        """POST JSON to a NetBox endpoint."""
        url = f"{self._base_url}{endpoint}"
        resp = self._session.post(url, json=payload, timeout=30)
        if resp.status_code == 409:
            raise requests.HTTPError(response=resp)
        if not resp.ok:
            log.error("POST %s → %d: %s", endpoint, resp.status_code, resp.text[:500])
        resp.raise_for_status()
        return resp.json()

    def _get(self, endpoint: str, params: str = "") -> Any:
        """GET from a NetBox endpoint."""
        url = f"{self._base_url}{endpoint}?{params}" if params else f"{self._base_url}{endpoint}"
        resp = self._session.get(url, timeout=30)
        resp.raise_for_status()
        return resp.json()

    def _get_or_create(
        self, endpoint: str, payload: dict, lookup_field: str,
        lookup_value: str, extra_filter: str = "",
    ) -> dict:
        """Find existing object or create new one. Handles 409 duplicates."""
        # Try to find existing
        url = f"{self._base_url}{endpoint}?{lookup_field}={lookup_value}{extra_filter}&limit=1"
        resp = self._session.get(url, timeout=30)
        resp.raise_for_status()
        results = resp.json().get("results", [])
        if results:
            log.debug("Found existing %s=%s id=%s", lookup_field, lookup_value, results[0]["id"])
            return results[0]

        # Create new
        try:
            return self._post(endpoint, payload)
        except requests.HTTPError as e:
            if e.response is not None and e.response.status_code == 400:
                # Might be a race condition; try lookup again
                resp = self._session.get(url, timeout=30)
                resp.raise_for_status()
                results = resp.json().get("results", [])
                if results:
                    return results[0]
            raise

    def _cache_id(self, category: str, name: str, obj_id: int) -> None:
        """Store an ID in the local cache."""
        if category not in self._id_cache:
            self._id_cache[category] = {}
        self._id_cache[category][name] = obj_id

    def _get_cached_id(self, category: str, name: str) -> int | None:
        """Retrieve an ID from the local cache."""
        return self._id_cache.get(category, {}).get(name)
